// https://agriculture.gouv.fr/linventaire-national-des-ressources-genetiques-forestieres
// Liste des espèces d’arbres forestiers
const hexagone = [
    {nom:"du sapin", booleen:true},
    {nom:"des sapins", booleen:true},
    {nom:"du cyprès", booleen:true},
    {nom:"des cyprès", booleen:true},
    {nom:"du genévrier", booleen:true},
    {nom:"des genévriers", booleen:true},
    {nom:"du mélèze", booleen:true},
    {nom:"des mélèzes", booleen:true},
    {nom:"de l’épicéa", booleen:true},
    {nom:"des épicéas", booleen:true},
    {nom:"du pin", booleen:true},
    {nom:"des pins", booleen:true},
    {nom:"de l’if", booleen:true},
    {nom:"des ifs", booleen:true},
    {nom:"de l’érable", booleen:true},
    {nom:"des érables", booleen:true},
    {nom:"de l’aulne", booleen:true},
    {nom:"des aulnes", booleen:true},
    {nom:"de l’arbousier", booleen:true},
    {nom:"des arbousiers", booleen:true},
    {nom:"du bouleau", booleen:true},
    {nom:"des bouleaux", booleen:true},
    {nom:"du charme", booleen:true},
    {nom:"des charmes", booleen:true},
    {nom:"du chataîgner", booleen:true},
    {nom:"des chataîgners", booleen:true},
    {nom:"du cornouiller", booleen:true},
    {nom:"des cornouillers", booleen:true},
    {nom:"de l’aubépine", booleen:true},
    {nom:"des aubépines", booleen:true},
    {nom:"de l’hêtre", booleen:true},
    {nom:"des hêtres", booleen:true},
    {nom:"du frêne à fleurs", booleen:true},
    {nom:"des frênes à fleurs", booleen:true},
    {nom:"du houx", booleen:true},
    {nom:"du noyer", booleen:true},
    {nom:"des noyers", booleen:true},
    {nom:"du cytise", booleen:true},
    {nom:"des cytises", booleen:true},
    {nom:"du pommier sauvage", booleen:true},
    {nom:"des pommiers sauvages", booleen:true},
    {nom:"de l’olivier", booleen:true},
    {nom:"des oliviers", booleen:true},
    {nom:"du charme", booleen:true},
    {nom:"des charmes", booleen:true},
    {nom:"du peuplier blanc", booleen:true},
    {nom:"des peupliers blancs", booleen:true},
    {nom:"du peuplier noir", booleen:true},
    {nom:"des peupliers noirs", booleen:true},
    {nom:"du peuplier grisard", booleen:true},
    {nom:"des peupliers grisards", booleen:true},
    {nom:"du tremble", booleen:true},
    {nom:"des trembles", booleen:true},
    {nom:"du merisier", booleen:true},
    {nom:"des merisiers", booleen:true},
    {nom:"du prunier de Briançon", booleen:true},
    {nom:"des pruniers de Briançon", booleen:true},
    {nom:"du laurier du Portugal", booleen:true},
    {nom:"des lauriers du Portugal", booleen:true},
    {nom:"du cerisier à grappes", booleen:true},
    {nom:"des cerisiers à grappes", booleen:true},
    {nom:"du poirier", booleen:true},
    {nom:"des poiriers", booleen:true},
    {nom:"du poirier à feuille d’amandier", booleen:true},
    {nom:"des poiriers à feuille d’amandier", booleen:true},
    {nom:"du chêne", booleen:true},
    {nom:"des chênes", booleen:true},
    {nom:"du chêne chevelu", booleen:true},
    {nom:"des chênes chevelus", booleen:true},
    {nom:"du chêne noir", booleen:true},
    {nom:"des chênes noirs", booleen:true},
    {nom:"du chêne vert", booleen:true},
    {nom:"des chênes verts", booleen:true},
    {nom:"du chêne tauzin", booleen:true},
    {nom:"des chênes tauzins", booleen:true},
    {nom:"du chêne des Pyrénées", booleen:true},
    {nom:"des chênes des Pyrénées", booleen:true},
    {nom:"du chêne à feuilles rondes", booleen:true},
    {nom:"des chênes à feuilles rondes", booleen:true},
    {nom:"du chêne-liège", booleen:true},
    {nom:"des chênes-lièges", booleen:true},
    {nom:"du saule blanc", booleen:true},
    {nom:"des saules blancs", booleen:true},
    {nom:"du saule cassant", booleen:true},
    {nom:"des saules cassants", booleen:true},
    {nom:"du saule à cinq étamines", booleen:true},
    {nom:"des saules à cinq étamines", booleen:true},
    {nom:"du saule des vanniers", booleen:true},
    {nom:"des saules des vanniers", booleen:true},
    {nom:"du sureau noir", booleen:true},
    {nom:"des sureaux noirs", booleen:true},
    {nom:"de l’alisier blanc", booleen:true},
    {nom:"des alisiers blancs", booleen:true},
    {nom:"de l’alisier de Bourgogne", booleen:true},
    {nom:"des alisiers de Bourgogne", booleen:true},
    {nom:"du sorbier des oiseleurs", booleen:true},
    {nom:"des sorbiers des oiseleurs", booleen:true},
    {nom:"du cormier", booleen:true},
    {nom:"des cormiers", booleen:true},
    {nom:"de l’alisier de Fontainebleau", booleen:true},
    {nom:"des alisiers de Fontainebleau", booleen:true},
    {nom:"de l’alisier de Mougeot", booleen:true},
    {nom:"des alisiers de Mougeot", booleen:true},
    {nom:"de l’alisier torminal", booleen:true},
    {nom:"des alisiers torminaux", booleen:true},
    {nom:"du tamaris de France", booleen:true},
    {nom:"des tamaris de France", booleen:true},
    {nom:"du tilleul à petites fleurs", booleen:true},
    {nom:"des tilleuls à petites fleurs", booleen:true},
    {nom:"du tilleul à grandes fleurs", booleen:true},
    {nom:"des tilleuls à grandes fleurs", booleen:true},
    {nom:"de l’orme de montagne", booleen:true},
    {nom:"des ormes de montagne", booleen:true},
    {nom:"de l’orme lisse", booleen:true},
    {nom:"des ormes lisses", booleen:true},
    {nom:"de l’orme champêtre", booleen:true},
    {nom:"des ormes champêtres", booleen:true},
    {nom:"du cèdre de l’Atlas", booleen:true},
    {nom:"des cèdres de l’Atlas", booleen:true},
    {nom:"du mélèze du Japon", booleen:true},
    {nom:"des mélèzes du Japon", booleen:true},
    {nom:"de l’épicéa de Sitka", booleen:true},
    {nom:"des épicéas de Sitka", booleen:true},
    {nom:"du pin noir d’Autriche", booleen:true},
    {nom:"des pins noirs d’Autriche", booleen:true},
    {nom:"du peuplier hybride", booleen:true},
    {nom:"des peupliers hybrides", booleen:true},
    {nom:"du peuplier deltoïde", booleen:true},
    {nom:"des peupliers deltoïdes", booleen:true},
    {nom:"du peuplier baumier", booleen:true},
    {nom:"des peupliers baumiers", booleen:true},
    {nom:"du chêne rouge", booleen:true},
    {nom:"des chênes rouges", booleen:true},
    {nom:"du sapin de la mer noire", booleen:true},
    {nom:"des sapins de la mer noire", booleen:true},
    {nom:"du sapin de Céphalonie", booleen:true},
    {nom:"des sapins de Céphalonie", booleen:true},
    {nom:"du sapin de Cilicie", booleen:true},
    {nom:"des sapins de Cilicie", booleen:true},
    {nom:"du sapin du Colorado", booleen:true},
    {nom:"des sapins du Colorado", booleen:true},
    {nom:"du sapin de Vancouver", booleen:true},
    {nom:"des sapins de Vancouver", booleen:true},
    {nom:"du sapin de Numidie", booleen:true},
    {nom:"des sapins de Numidie", booleen:true},
    {nom:"du sapin noble", booleen:true},
    {nom:"des sapins nobles", booleen:true},
    {nom:"du calocèdre", booleen:true},
    {nom:"des calocèdres", booleen:true},
    {nom:"du cèdre de Chypre", booleen:true},
    {nom:"des cèdres de Chypre", booleen:true},
    {nom:"du cèdre de l’Himalaya", booleen:true},
    {nom:"des cèdres de l’Himalaya", booleen:true},
    {nom:"du cèdre du Liban", booleen:true},
    {nom:"des cèdres du Liban", booleen:true},
    {nom:"du cyprès de Lawson", booleen:true},
    {nom:"des cyprès de Lawson", booleen:true},
    {nom:"du cryptomère du Japon", booleen:true},
    {nom:"des cryptomères du Japon", booleen:true},
    {nom:"du cyprès de Leyland", booleen:true},
    {nom:"des cyprès de Leyland", booleen:true},
    {nom:"du cyprès de l’Arizona", booleen:true},
    {nom:"des cyprès de l’Arizona", booleen:true},
    {nom:"du cyprès de l’Atlas", booleen:true},
    {nom:"des cyprès de l’Atlas", booleen:true},
    {nom:"du cyprès du Tassili", booleen:true},
    {nom:"des cyprès de Tassili", booleen:true},
    {nom:"du cyprès de Lambert", booleen:true},
    {nom:"des cyprès de Lambert", booleen:true},
    {nom:"du sapin d’eau", booleen:true},
    {nom:"des sapins d’eau", booleen:true},
    {nom:"du pin de Calabre", booleen:true},
    {nom:"des pins de Calabre", booleen:true},
    {nom:"du pin de Murray", booleen:true},
    {nom:"des pins de Murray", booleen:true},
    {nom:"du pin de Monterrey", booleen:true},
    {nom:"des pins de Monterrey", booleen:true},
    {nom:"du pin dur du Nord", booleen:true},
    {nom:"des pins durs du Nord", booleen:true},
    {nom:"du pin Weymouth", booleen:true},
    {nom:"des pins Weymouth", booleen:true},
    {nom:"du pin à encens", booleen:true},
    {nom:"des pins à encens", booleen:true},
    {nom:"du séquoia géant", booleen:true},
    {nom:"des séquoias géants", booleen:true},
    {nom:"du cyprès chauve", booleen:true},
    {nom:"des cyprès chauves", booleen:true},
    {nom:"du thuya géant", booleen:true},
    {nom:"des thuyas géants", booleen:true},
    {nom:"du mimosa", booleen:true},
    {nom:"des mimosas", booleen:true},
    {nom:"de l’érable negundo ", booleen:true},
    {nom:"des érables negundos", booleen:true},
    {nom:"du marronnier d’Inde", booleen:true},
    {nom:"des marronniers d’Inde", booleen:true},
    {nom:"de l’ailante", booleen:true},
    {nom:"des ailantes", booleen:true},
    {nom:"du micocoulier", booleen:true},
    {nom:"des micocouliers", booleen:true},
    {nom:"de l’eucalyptus", booleen:true},
    {nom:"des eucalyptus", booleen:true},
    {nom:"du févier d’Amérique", booleen:true},
    {nom:"des féviers d’Amérique", booleen:true},
    {nom:"du noyer noir", booleen:true},
    {nom:"des noyers noirs", booleen:true},
    {nom:"du Liquidambar", booleen:true},
    {nom:"des liquidambars", booleen:true},
    {nom:"du tulipier de Virginie", booleen:true},
    {nom:"des tulipiers de Virginie", booleen:true},
    {nom:"du platane d’Orient", booleen:true},
    {nom:"des platanes d’Orient", booleen:true},
    {nom:"du platane hybride", booleen:true},
    {nom:"des platanes hybrides", booleen:true},
    {nom:"du laurier cerise", booleen:true},
    {nom:"des lauriers cerise", booleen:true},
    {nom:"du cerisier tardif", booleen:true},
    {nom:"des cerisiers tardifs", booleen:true},
    {nom:"du chêne des marais", booleen:true},
    {nom:"des chênes des marais", booleen:true},
];

const guadeloupeMartinique = [
    {nom:"de l’ananas sauvage", booleen:true},
    {nom:"des ananas sauvages", booleen:true},
    {nom:"du chou-piquant", booleen:true},
    {nom:"des choux-piquants", booleen:true},
    {nom:"du bois rouge", booleen:true},
    {nom:"des bois rouges", booleen:true},
    {nom:"de l’angelin", booleen:true},
    {nom:"des angelins", booleen:true},
    {nom:"du laurier falaise", booleen:true},
    {nom:"de la petite siguine", booleen:true},
    {nom:"du bois-chique", booleen:true},
    {nom:"du calumet montagne", booleen:true},
    {nom:"du mangle blanc", booleen:true},
    {nom:"de l’outi grand bois", booleen:true},
    {nom:"du bois gligli", booleen:true},
    {nom:"du buis", booleen:true},
    {nom:"du mauricif", booleen:true},
    {nom:"du pompon rouge", booleen:true},
    {nom:"des pompons rouges", booleen:true},
    {nom:"du bois-ti feuilles", booleen:true},
    {nom:"du bois-cannelle", booleen:true},
    {nom:"de l’acajou rouge", booleen:true},
    {nom:"des acajous rouges", booleen:true},
    {nom:"du fuschia-montagne", booleen:true},
    {nom:"du crécré rouge", booleen:true},
    {nom:"des crécrés rouges", booleen:true},
    {nom:"de l’acomat pays", booleen:true},
    {nom:"du crécré rouge-montagne", booleen:true},
    {nom:"du mangle-montagne", booleen:true},
    {nom:"de l’aralie rose", booleen:true},
    {nom:"du raisinier grande feuille", booleen:true},
    {nom:"du latanier", booleen:true},
    {nom:"du bois mabi", booleen:true},
    {nom:"du cypre", booleen:true},
    {nom:"des cypres", booleen:true},
    {nom:"des zyeux à crabe", booleen:true},
    {nom:"du caca-ravet", booleen:true},
    {nom:"du gommier blanc", booleen:true},
    {nom:"des gommiers blancs", booleen:true},
    {nom:"du bois-moussara", booleen:true},
    {nom:"du vanillier marron", booleen:true},
    {nom:"de la cerise montagne", booleen:true},
    {nom:"du bois grillé", booleen:true},
    {nom:"du palmiste", booleen:true},
    {nom:"des palmistes", booleen:true},
    {nom:"du génipa", booleen:true},
    {nom:"du coco-macaque", booleen:true},
    {nom:"du gaïac", booleen:true},
    {nom:"du bois-pistolet", booleen:true},
    {nom:"du corrosol grand bois", booleen:true},
    {nom:"du zicaque poilu", booleen:true},
    {nom:"du bois d’Amande", booleen:true},
    {nom:"du courbaril", booleen:true},
    {nom:"du citronnier montagne", booleen:true},
    {nom:"du bois-citron", booleen:true},
    {nom:"du bois de fer", booleen:true},
    {nom:"du bois à pian", booleen:true},
    {nom:"du mûrier pays", booleen:true},
    {nom:"du balata", booleen:true},
    {nom:"du café-bois", booleen:true},
    {nom:"du bois de sept ans", booleen:true},
    {nom:"du crécré savanne", booleen:true},
    {nom:"du crécré montagne", booleen:true},
    {nom:"du caconier", booleen:true},
    {nom:"du laurier mangle", booleen:true},
    {nom:"du bâtard de fougère", booleen:true},
    {nom:"du bois-flot", booleen:true},
    {nom:"du poiret", booleen:true},
    {nom:"du bois amer", booleen:true},
    {nom:"du petit mapou", booleen:true},
    {nom:"de l’ananas rouge montagne", booleen:true},
    {nom:"du barac", booleen:true},
    {nom:"du contrevent", booleen:true},
    {nom:"du bois L’encens", booleen:true},
    {nom:"du bois-noyaux", booleen:true},
    {nom:"du mangle médaille", booleen:true},
    {nom:"du bois-lélé", booleen:true},
    {nom:"du ti-coco", booleen:true},
    {nom:"du marbri", booleen:true},
    {nom:"du petit bri", booleen:true},
    {nom:"du bois citron", booleen:true},
    {nom:"du chataîgner grandes feuilles", booleen:true},
    {nom:"des chataîgners grandes feuilles", booleen:true},
    {nom:"du bois-chique", booleen:true},
    {nom:"du laurier orange", booleen:true},
    {nom:"du magnolia", booleen:true},
    {nom:"des magnolias", booleen:true},
    {nom:"du poirier", booleen:true},
    {nom:"du bois-lézard", booleen:true},
    {nom:"du bois-capitaine", booleen:true},
    {nom:"de l’acacia-rivière", booleen:true},
];

const saintPierreMiquelon = [
    {nom:"du sapin baumier", booleen:true},
    {nom:"de l’érable à épis", booleen:true},
    {nom:"des érables à épis", booleen:true},
    {nom:"de l’aulne crispé", booleen:true},
    {nom:"des aulnes crispés", booleen:true},
    {nom:"de l’amélanchier", booleen:true},
    {nom:"des amélanchiers", booleen:true},
    {nom:"du bouleau jaune", booleen:true},
    {nom:"des bouleaux jaunes", booleen:true},
    {nom:"du bouleau blanc", booleen:true},
    {nom:"des bouleaux blancs", booleen:true},
    {nom:"du bouleau nain", booleen:true},
    {nom:"des bouleaux nains", booleen:true},
    {nom:"du genévrier horizontal", booleen:true},
    {nom:"des genévriers horizontaux", booleen:true},
    {nom:"du mélèze laricin", booleen:true},
    {nom:"des mélèzes laricins", booleen:true},
    {nom:"de l’épicéa blanc", booleen:true},
    {nom:"des épicéas blancs", booleen:true},
    {nom:"de l’épicéa noir", booleen:true},
    {nom:"des épicéas noirs", booleen:true},
    {nom:"du cerisier de Pennsylvanie", booleen:true},
    {nom:"des cerisiers de Pennsylvanie", booleen:true},
    {nom:"du cerisier de Virginie", booleen:true},
    {nom:"des cerisiers de Virginie", booleen:true},
    {nom:"du saule", booleen:true},
    {nom:"des saules", booleen:true},
    {nom:"du sorbier d’Amérique", booleen:true},
    {nom:"des sorbiers d’Amérique", booleen:true},
    {nom:"de l’if du Canada", booleen:true}
];

const polynesie = [
    {nom:"du tamanu", booleen:true},
    {nom:"du bois de fer", booleen:true},
    {nom:"du cocotier", booleen:true},
    {nom:"des cocotiers", booleen:true},
    {nom:"du falcata", booleen:true},
    {nom:"du purau", booleen:true},
    {nom:"du mape", booleen:true},
    {nom:"du tou", booleen:true},
    {nom:"du fara", booleen:true},
    {nom:"du santal", booleen:true},
    {nom:"du bois de rose d’Océanie", booleen:true},
];

const wallis = [
    {nom:"du cardinalier", booleen:true},
    {nom:"des cardinaliers", booleen:true},
    {nom:"du kaori de forêt", booleen:true},
    {nom:"du kaori blanc", booleen:true},
    {nom:"du bois noir", booleen:true},
    {nom:"du bancoulier", booleen:true},
    {nom:"du pin colonnaire", booleen:true},
    {nom:"des pins colonnaires", booleen:true},
    {nom:"de l’arbre à pain", booleen:true},
    {nom:"des arbres à pain", booleen:true},
    {nom:"du neem", booleen:true},
    {nom:"du bonnet d’évêque", booleen:true},
    {nom:"du murier à papier", booleen:true},
    {nom:"du palétuvier noir", booleen:true},
    {nom:"des palétuviers noirs", booleen:true},
    {nom:"du tamanou", booleen:true},
    {nom:"de l’ylang ylang", booleen:true},
    {nom:"du fromager", booleen:true},
    {nom:"du faux manguier", booleen:true},
    {nom:"du noyer du pacifique", booleen:true},
    {nom:"du flamboyant", booleen:true},
    {nom:"du kaukauli", booleen:true},
    {nom:"du kulume", booleen:true},
    {nom:"du cerisier bleu", booleen:true},
    {nom:"du filimoto", booleen:true},
    {nom:"de l’érythrine", booleen:true},
    {nom:"du banian", booleen:true},
    {nom:"des banians", booleen:true},
    {nom:"du figuier des teinturiers", booleen:true},
    {nom:"des figuiers des teinturiers", booleen:true},
    {nom:"de l’arbre lanterne", booleen:true},
    {nom:"du bourao", booleen:true},
    {nom:"du chataîgner tahitien", booleen:true},
    {nom:"des chataîgners tahitiens", booleen:true},
    {nom:"du kohu", booleen:true},
    {nom:"du faux acacia", booleen:true},
    {nom:"des faux acacias", booleen:true},
    {nom:"du manguier", booleen:true},
    {nom:"des manguiers", booleen:true},
    {nom:"du karanj", booleen:true},
    {nom:"du noni", booleen:true},
    {nom:"du cerisier de Jamaïque", booleen:true},
    {nom:"des cerisiers de Jamaïque", booleen:true},
    {nom:"du frangipanier", booleen:true},
    {nom:"des frangipaniers", booleen:true},
    {nom:"du lychee sauvage", booleen:true},
    {nom:"des lychees sauvages", booleen:true},
    {nom:"du goyaver", booleen:true},
    {nom:"des goyavers", booleen:true},
    {nom:"du palétuvier", booleen:true},
    {nom:"des palétuviers", booleen:true},
    {nom:"du sumac", booleen:true},
    {nom:"de la pomme-rouge", booleen:true},    
    {nom:"des pommes-rouges", booleen:true},
    {nom:"du badamier", booleen:true},
    {nom:"des badamiers", booleen:true},
    {nom:"du bois de rose d’Océanie", booleen:true},
    {nom:"des bois de roses d’Océanie", booleen:true}
];

const laReunion = [
    {nom:"de l’abélie à grandes fleurs", booleen:true},
    {nom:"du tamarin des hauts", booleen:true},
    {nom:"des tamarins des hauts", booleen:true},
    {nom:"de l’acacia", booleen:true},
    {nom:"des acacias", booleen:true},
    {nom:"de l’acacia rouge", booleen:true},
    {nom:"des acacias rouges", booleen:true},
    {nom:"du bois de Charles", booleen:true},
    {nom:"du bois noir rouge", booleen:true},
    {nom:"du baobab", booleen:true},
    {nom:"des baobabs", booleen:true},
    {nom:"du petit bois de rempart", booleen:true},
    {nom:"du bois de rempart", booleen:true},
    {nom:"du bois noir", booleen:true},
    {nom:"de l’arbre à pluie", booleen:true},
    {nom:"du bois de merle", booleen:true},
    {nom:"de l’aulne de Corse", booleen:true},
    {nom:"des aulnes de Corse", booleen:true},
    {nom:"du chérimole", booleen:true},
    {nom:"de l’atemoya", booleen:true},
    {nom:"du sapoty", booleen:true},
    {nom:"du cœur de bœuf", booleen:true},
    {nom:"des cœurs de bœuf", booleen:true},
    {nom:"du bois de cabri blanc", booleen:true},
    {nom:"du bois d’osto", booleen:true},
    {nom:"du change-écorce", booleen:true},
    {nom:"du bois de Noël", booleen:true},
    {nom:"du coq du Levant", booleen:true},
    {nom:"des coqs du Levant", booleen:true},
    {nom:"du fruit à pain", booleen:true},
    {nom:"des fruits à pain", booleen:true},
    {nom:"du bois de savon", booleen:true},
    {nom:"du bonnet de prêtre", booleen:true},
    {nom:"des bonnets de prêtre", booleen:true},
    {nom:"du bois d’oiseau", booleen:true},
    {nom:"du bois de raisin", booleen:true},
    {nom:"du bois chapelet", booleen:true},
    {nom:"du bois de source blanc", booleen:true},
    {nom:"du bougainvillée", booleen:true},
    {nom:"des bougainvillées", booleen:true},
    {nom:"de l’arbre aux papillons", booleen:true},
    {nom:"du sappan", booleen:true},
    {nom:"des sappans", booleen:true},
    {nom:"du petit flamboyant", booleen:true},
    {nom:"des petits flamboyants", booleen:true},
    {nom:"du rince-bouteille", booleen:true},
    {nom:"du pacanier", booleen:true},
    {nom:"des pacaniers", booleen:true},
    {nom:"du laurier jaune", booleen:true},
    {nom:"des lauriers jaunes", booleen:true},
    {nom:"du bois de cabri", booleen:true},
    {nom:"du cytise indien", booleen:true},
    {nom:"des cytises indiens", booleen:true},
    {nom:"du casse rose de Java", booleen:true},
    {nom:"de la chataîgne", booleen:true},
    {nom:"des chataîgnes", booleen:true},
    {nom:"du filao pays", booleen:true},
    {nom:"des filaos pays", booleen:true},
    {nom:"du glauca", booleen:true},
    {nom:"des glaucas", booleen:true},
    {nom:"du filao multipliant", booleen:true},
    {nom:"des filaos multipliants", booleen:true},
    {nom:"du cecropia", booleen:true},
    {nom:"des cecropias", booleen:true},
    {nom:"de l’ouatier", booleen:true},
    {nom:"des ouatiers", booleen:true},
    {nom:"du bois de corail", booleen:true},
    {nom:"des bois de corail", booleen:true},
    {nom:"du bois de lousteau", booleen:true},
    {nom:"du bois de cœur bleu", booleen:true},
    {nom:"du bois de cœur bleu des hauts", booleen:true},
    {nom:"du bois de cœur bleu des bas", booleen:true},
    {nom:"de l’icaquier", booleen:true},
    {nom:"des icaquiers", booleen:true},
    {nom:"de la pomme de lait", booleen:true},
    {nom:"des pommes de lait", booleen:true},
    {nom:"de la quinquina", booleen:true},
    {nom:"du camphre", booleen:true},
    {nom:"des camphres", booleen:true},
    {nom:"du cannelier", booleen:true},
    {nom:"des canneliers", booleen:true},
    {nom:"du citron galet", booleen:true},
    {nom:"de la bigarade", booleen:true},
    {nom:"du bigaradier", booleen:true},
    {nom:"des bigaradiers", booleen:true},
    {nom:"du combava", booleen:true},
    {nom:"des combavas", booleen:true},
    {nom:"du citron", booleen:true},
    {nom:"des citrons", booleen:true},
    {nom:"du pomelo", booleen:true},
    {nom:"des pomelos", booleen:true},
    {nom:"du cédrat", booleen:true},
    {nom:"des cédrats", booleen:true},
    {nom:"de l’orange", booleen:true},
    {nom:"des oranges", booleen:true},
    {nom:"de l’oranger", booleen:true},
    {nom:"des orangers", booleen:true},    
    {nom:"de la vangassaye", booleen:true},
    {nom:"du mandarinier", booleen:true},
    {nom:"des mandariniers", booleen:true},
    {nom:"du pamplemoussier", booleen:true},
    {nom:"des pamplemoussiers", booleen:true},
    {nom:"du gros bois d’oiseaux", booleen:true},
    {nom:"du bois d’oiseaux", booleen:true},
    {nom:"du grand bois cassant", booleen:true},
    {nom:"des grands bois cassants", booleen:true},
    {nom:"du sapote chinois", booleen:true},
    {nom:"des sapotes chinois", booleen:true},
    {nom:"de l’arbre autographe", booleen:true},
    {nom:"du raisin de mer", booleen:true},
    {nom:"des raisins de mer", booleen:true},
    {nom:"du café", booleen:true},
    {nom:"des cafés", booleen:true},
    {nom:"du café Libéria", booleen:true},
    {nom:"du café marron", booleen:true},
    {nom:"du colatier", booleen:true},
    {nom:"des colatiers", booleen:true},
    {nom:"du flamboyant d’Avril", booleen:true},
    {nom:"des flamboyants d’Avril", booleen:true},
    {nom:"de l’aigrette de Madagascar", booleen:true},
    {nom:"des aigrettes de Madagascar", booleen:true},
    {nom:"du bois de pintade", booleen:true},
    {nom:"du bois de perroquet", booleen:true},
    {nom:"du chêne noir", booleen:true},
    {nom:"des chênes noirs", booleen:true},
    {nom:"du bois savon", booleen:true},
    {nom:"du sébestier", booleen:true},
    {nom:"des sébestiers", booleen:true},
    {nom:"du mapou rouge", booleen:true},
    {nom:"du noisetier", booleen:true},
    {nom:"des noisetiers", booleen:true},
    {nom:"du bois de judas", booleen:true},
    {nom:"du calebassier des Antilles", booleen:true},
    {nom:"des calebassiers des Antilles", booleen:true},
    {nom:"du bois de senteur", booleen:true},
    {nom:"de la liane à caoutchouc", booleen:true},
    {nom:"du cyprès de Lambert", booleen:true},
    {nom:"des cyprès de Lambert", booleen:true},
    {nom:"du genêt à balai", booleen:true},
    {nom:"des genêts à balai", booleen:true},
    {nom:"du palissandre", booleen:true},
    {nom:"des palissandres", booleen:true},
    {nom:"du bois malgache", booleen:true},
    {nom:"des bois malgaches", booleen:true},
    {nom:"du kéké", booleen:true},
    {nom:"du baboul", booleen:true},
    {nom:"du longani", booleen:true},
    {nom:"des longanis", booleen:true},
    {nom:"du longanier", booleen:true},
    {nom:"des longaniers", booleen:true},
    {nom:"du kaki", booleen:true},
    {nom:"des kakis", booleen:true},
    {nom:"du mahot tantan", booleen:true},
    {nom:"du mahot blanc", booleen:true},
    {nom:"du mahot bleu", booleen:true},
    {nom:"du mahot rose", booleen:true},
    {nom:"du petit mahot noir", booleen:true},
    {nom:"du mahot", booleen:true},
    {nom:"des mahots", booleen:true},
    {nom:"du mahot rouge", booleen:true},
    {nom:"du mahot noir", booleen:true},
    {nom:"de l’olivier de Ceylan", booleen:true},
    {nom:"des oliviers de Ceylan", booleen:true},
    {nom:"du bois rouge", booleen:true},
    {nom:"de l’oreille cafre", booleen:true},
    {nom:"du thym marron", booleen:true},
    {nom:"de la bibasse", booleen:true},
    {nom:"du pignon d’Inde", booleen:true},
    {nom:"des pignons d’Inde", booleen:true},
    {nom:"du bois d’huile", booleen:true},
    {nom:"du bois de rongue", booleen:true},
    {nom:"du bois de ronde", booleen:true},
    {nom:"de l’eucalyptus citronelle", booleen:true},
    {nom:"de l’eucalyptus rouge", booleen:true},
    {nom:"des eucalyptus rouges", booleen:true},
    {nom:"de la cerise créole", booleen:true},
    {nom:"de l’esquine", booleen:true},
    {nom:"du banian", booleen:true},
    {nom:"des banians", booleen:true},
    {nom:"du figuier pleureur", booleen:true},
    {nom:"des figuiers pleureurs", booleen:true},
    {nom:"du caoutchouc", booleen:true},
    {nom:"du figuier blanc", booleen:true},
    {nom:"des figuiers blancs", booleen:true},
    {nom:"de l’arbre de l’intendance", booleen:true},
    {nom:"des arbres de l’intendance", booleen:true},
    {nom:"de l’affouche", booleen:true},
    {nom:"de l’affouche rouge", booleen:true},
    {nom:"de la prune malgache", booleen:true},
    {nom:"du bois puant", booleen:true},
    {nom:"du bois de Laurent Martin", booleen:true},
    {nom:"du kumquat rond", booleen:true},
    {nom:"du kumquat long", booleen:true},
    {nom:"du gardenia", booleen:true},
    {nom:"des gardenias", booleen:true},
    {nom:"du bois bleu", booleen:true},
    {nom:"du bois de piment", booleen:true},
    {nom:"du petit bois de rat", booleen:true},
    {nom:"du bois de punaise", booleen:true},
    {nom:"du lait de la Vierge", booleen:true},
    {nom:"du bois de source", booleen:true},
    {nom:"du bois de campêche", booleen:true},
    {nom:"de l’arbre à caoutchouc", booleen:true},
    {nom:"du foulsapate marron", booleen:true},
    {nom:"du mahot bâtard", booleen:true},
    {nom:"de la fleur de Saint Loouis", booleen:true},
    {nom:"de la passerose", booleen:true},
    {nom:"des passeroses", booleen:true},
    {nom:"de l’hibiscus", booleen:true},
    {nom:"des hibiscus", booleen:true},
    {nom:"de l’hovénie sucrée", booleen:true},
    {nom:"de l’ambaville", booleen:true},
    {nom:"des ambavilles", booleen:true},
    {nom:"de l’hortensia", booleen:true},
    {nom:"des hortensias", booleen:true},
    {nom:"du millepertuis", booleen:true},
    {nom:"de l’indigotier sauvage", booleen:true},
    {nom:"de l’indigo", booleen:true},
    {nom:"de l’arbre à miel", booleen:true},
    {nom:"du jacaranda", booleen:true},
    {nom:"des jacarandas", booleen:true},
    {nom:"du jasmin", booleen:true},
    {nom:"des jasmins", booleen:true},
    {nom:"de l’arbre corail", booleen:true},
    {nom:"du noyer d’Amérique", booleen:true},
    {nom:"des noyers d’Amérique", booleen:true},
    {nom:"du noyer", booleen:true},
    {nom:"des noyers", booleen:true},
    {nom:"du cyprès", booleen:true},
    {nom:"des cyprès", booleen:true},
    {nom:"du genévrier de Virginie", booleen:true},
    {nom:"des genévrier de Virginie", booleen:true},
    {nom:"de l’arbre à saucisses", booleen:true},
    {nom:"des arbres à saucisses", booleen:true},
    {nom:"du petit goyavier fleur", booleen:true},
    {nom:"de l’avocat marron", booleen:true},
    {nom:"de la souveraine de mer", booleen:true},
    {nom:"du bois de maman", booleen:true},
    {nom:"du petit houx", booleen:true},
    {nom:"du cerisier des Antilles", booleen:true},
    {nom:"du pommier", booleen:true},
    {nom:"des pommiers", booleen:true},
    {nom:"de l’hibiscus piment", booleen:true},
    {nom:"de l’abricotier de Saint Domingue", booleen:true},
    {nom:"du manguier", booleen:true},
    {nom:"des manguiers", booleen:true},
    {nom:"de la sapotille", booleen:true},
    {nom:"du bois de catafaille", booleen:true},
    {nom:"du bois de chenilles", booleen:true},
    {nom:"du bois de paille-en-queue", booleen:true},
    {nom:"du mapou des hauts", booleen:true},
    {nom:"de la marguerite de mai", booleen:true},
    {nom:"du mûrier", booleen:true},
    {nom:"des mûriers", booleen:true},
    {nom:"du bois ramier", booleen:true},
    {nom:"du cerisier de Panama", booleen:true},
    {nom:"des cerisiers de Panama", booleen:true},
    {nom:"du muscadier", booleen:true},
    {nom:"des muscadiers", booleen:true},
    {nom:"du ramboutan", booleen:true},
    {nom:"du bois maigre", booleen:true},
    {nom:"du jasmin de nuit", booleen:true},
    {nom:"du bois d’ortie", booleen:true},
    {nom:"du bois jaune", booleen:true},
    {nom:"de la cannelle marron", booleen:true},
    {nom:"du bois d’effort", booleen:true},
    {nom:"du bois d’olive noir", booleen:true},
    {nom:"du bois d’olive blanc", booleen:true},
    {nom:"du petit vacoua", booleen:true},
    {nom:"du bois matelot", booleen:true},
    {nom:"de la raquette noire", booleen:true},
    {nom:"du bois de demoiselle", booleen:true},
    {nom:"du faux bois de demoiselle", booleen:true},
    {nom:"du bois mapou", booleen:true},
    {nom:"du tamarin d’Inde", booleen:true},
    {nom:"du bois de joli cœur", booleen:true},
    {nom:"du frangipanier blanc", booleen:true},
    {nom:"des frangipaniers blancs", booleen:true},
    {nom:"du frangipanier rouge", booleen:true},
    {nom:"des frangipaniers rouges", booleen:true},
    {nom:"du bois d’éponge", booleen:true},
    {nom:"du bois de banane", booleen:true},
    {nom:"du bois de papaye", booleen:true},
    {nom:"du bois blanc rouge", booleen:true},
    {nom:"du bois de fièvre", booleen:true},
    {nom:"de l’abricotier", booleen:true},
    {nom:"des abricotiers", booleen:true},
    {nom:"du cerisier", booleen:true},
    {nom:"des cerisiers", booleen:true},
    {nom:"de l’amandier", booleen:true},
    {nom:"des amandiers", booleen:true},
    {nom:"du pêcher", booleen:true},
    {nom:"des pêchers", booleen:true},
    {nom:"du bois cassant", booleen:true},
    {nom:"du gros bois cassant", booleen:true},
    {nom:"du bouillon blanc", booleen:true},
    {nom:"du bois de tabac", booleen:true},
    {nom:"du bois marron", booleen:true},
    {nom:"de la salière", booleen:true},
    {nom:"du goyavier", booleen:true},
    {nom:"des goyaviers", booleen:true},
    {nom:"du goyavier blanc", booleen:true},
    {nom:"des goyaviers blancs", booleen:true},
    {nom:"du grenadier", booleen:true},
    {nom:"des grenadiers", booleen:true},
    {nom:"du bois mussard", booleen:true},
    {nom:"du poirier", booleen:true},
    {nom:"des poiriers", booleen:true},
    {nom:"du chêne", booleen:true},
    {nom:"des chênes", booleen:true},
    {nom:"du chêne rouge d’Amérique", booleen:true},
    {nom:"des chênes rouges d’Amérique", booleen:true},
    {nom:"de l’acacia blanc", booleen:true},
    {nom:"des acacias blancs", booleen:true},
    {nom:"du bois de senteur blanc", booleen:true},
    {nom:"du saule de Babylone", booleen:true},
    {nom:"du saule pleureur", booleen:true},
    {nom:"du santal", booleen:true},
    {nom:"du savonnier", booleen:true},
    {nom:"de l’arbre ombrelle", booleen:true},
    {nom:"du faux poivrier", booleen:true},
    {nom:"des faux poivriers", booleen:true},
    {nom:"du bois de prune", booleen:true},
    {nom:"du bois de sinte", booleen:true},
    {nom:"du bois dur", booleen:true},
    {nom:"du manguier à grappes", booleen:true},
    {nom:"des manguiers à grappes", booleen:true},
    {nom:"du tulipier du Gabon", booleen:true},
    {nom:"des tulipiers du Gabon", booleen:true},
    {nom:"de la boule de neige", booleen:true},
    {nom:"des boules de neige", booleen:true},
    {nom:"du giroflier", booleen:true},
    {nom:"des girofliers", booleen:true},
    {nom:"du bois de pomme blanc", booleen:true},
    {nom:"du bois de pomme", booleen:true},
    {nom:"du bois de pomme rouge", booleen:true},
    {nom:"du petit bois de pomme", booleen:true},
    {nom:"du bois de lait", booleen:true},
    {nom:"du tamarin des bas", booleen:true},
    {nom:"du bois de bombarde", booleen:true},
    {nom:"du jasmin du Cap", booleen:true},
    {nom:"des jasmins du Cap", booleen:true},
    {nom:"du bois pissenlit", booleen:true},
    {nom:"de l’indigo blanc", booleen:true},
    {nom:"du badamier", booleen:true},
    {nom:"de l’orgueil de Bolivie", booleen:true},
    {nom:"de l’acajou de Chine", booleen:true},
    {nom:"du bois d’Andrèze", booleen:true},
    {nom:"du hérisson blanc", booleen:true},
    {nom:"du genêt", booleen:true},
    {nom:"des genêts", booleen:true},
    {nom:"du bois de chenilles", booleen:true},
    {nom:"du petit bois de tan", booleen:true},
    {nom:"bois de poivre", booleen:true},
    {nom:"de la jujube", booleen:true}
];

const liste = [...hexagone, ...guadeloupeMartinique, ...saintPierreMiquelon, ...polynesie, ...wallis, ...laReunion];
export default liste;
