// https://fr.wikipedia.org/wiki/Liste_des_Fran%C3%A7ais_laur%C3%A9ats_du_prix_Nobel
export default [
    {nom:"Frédéric Passy", booleen:true},
    {nom:"Sully Prudhomme", booleen:true},
    {nom:"Antoine Henri Becquerel", booleen:true},
    {nom:"Marie Curie", booleen:true},
    {nom:"Pierre Curie", booleen:true},
    {nom:"Frédéric Mistral", booleen:true},
    {nom:"Henri Moissan", booleen:true},
    {nom:"Louis Renault", booleen:true},
    {nom:"Charles Laveran", booleen:true},
    {nom:"Gabriel Lippmann", booleen:true},
    {nom:"Paul-Henri Balluet", booleen:true},
    {nom:"Marie Curie", booleen:true},
    {nom:"Alexis Carrel", booleen:true},
    {nom:"Victor Grignard", booleen:true},
    {nom:"Paul Sabatier", booleen:true},
    {nom:"Charles Richet", booleen:true},
    {nom:"Romain Rolland", booleen:true},
    {nom:"Léon Bourgeois", booleen:true},
    {nom:"Anatole France", booleen:true},
    {nom:"Aristide Briand", booleen:true},
    {nom:"Jean Perrin", booleen:true},
    {nom:"Ferdinand Buisson", booleen:true},
    {nom:"Henri Bergson", booleen:true},
    {nom:"Charles Nicolle", booleen:true},
    {nom:"Louis de Broglie", booleen:true},
    {nom:"Frédéric Joliot-Curie", booleen:true},
    {nom:"Irène Joliot-Curie", booleen:true},
    {nom:"Roger Martin du Gard", booleen:true},
    {nom:"André Gide", booleen:true},
    {nom:"Léon Jouhaux", booleen:true},
    {nom:"Albert Schweitzer", booleen:true},
    {nom:"François Mauriac", booleen:true},
    {nom:"André Frédéric Cournand", booleen:true},
    {nom:"Albert Camus", booleen:true},
    {nom:"Saint-John Perse", booleen:true},
    {nom:"Jean-Paul Sartre", booleen:true},
    {nom:"François Jacob", booleen:true},
    {nom:"André Lwoff", booleen:true},
    {nom:"Jacques Monod", booleen:true},
    {nom:"Alfred Kastler", booleen:true},
    {nom:"René Cassin", booleen:true},
    {nom:"Louis Néel", booleen:true},
    {nom:"Roger Guillemin", booleen:true},
    {nom:"Jean Dausset", booleen:true},
    {nom:"Gérard Debreu", booleen:true},
    {nom:"Claude Simon", booleen:true},
    {nom:"Jean-Marie Lehn", booleen:true},
    {nom:"Maurice Allais", booleen:true},
    {nom:"Pierre-Gilles de Gennes", booleen:true},
    {nom:"Georges Charpak", booleen:true},
    {nom:"Claude Cohen-Tannoudji", booleen:true},
    {nom:"Médecins sans frontières", booleen:true},
    {nom:"Gao Xingjian", booleen:true},
    {nom:"Yves Chauvin", booleen:true},
    {nom:"Albert Fert", booleen:true},
    {nom:"Françoise Barré-Sinoussi", booleen:true},
    {nom:"Luc Montagnier", booleen:true},
    {nom:"Jean-Marie Le Clézio", booleen:true},
    {nom:"Jules Hoffmann", booleen:true},
    {nom:"Serge Haroche", booleen:true},
    {nom:"Patrick Modiano", booleen:true},
    {nom:"Jean Tirole", booleen:true},
    {nom:"Jean-Pierre Sauvage", booleen:true},
    {nom:"Gérard Mourou", booleen:true},
    {nom:"Esther Duflo", booleen:true},
    {nom:"Emmanuelle Charpentier", booleen:true}
];
