//let a = { 0 : "zéro", 1 : "un", 2 : "deux", 3 : "trois", 4 : "quatre", 5 : "cinq", 6 : "six", 7 : "sept", 8 : "huit", 9 : "neuf", 10 : "dix"};

// module.exports = {

// 0 : "zéro", 
// 1 : "un", 
// 2 : "deux", 
// 3 : "trois", 
// 4 : "quatre", 
// 5 : "cinq", 
// 6 : "six", 
// 7 : "sept", 
// 8 : "huit", 
// 9 : "neuf", 
// 10 : "dix", 
// 11 : "onze", 
// 12 : "douze", 
// 13 : "treize", 
// 14 : "quatorze", 
// 15 : "quinze", 
// 16 : "seize", 
// 17 : "dix-sept", 
// 18 : "dix-huit", 
// 19 : "dix-neuf", 
// 20 : "vingt", 
// 21 : "vingt-et-un", 
// 22 : "vingt-deux", 
// 23 : "vingt-trois", 
// 24 : "vingt-quatre", 
// 25 : "vint-cinq", 
// 26 : "vingt-six", 
// 27 : "vingt-sept", 
// 28 : "vingt-huit", 
// 29 : "vingt-neuf", 
// 30 : "trente"
// };

const liste = [
    [0,"zéro"],
    [1,"un"],
    [2,"deux"],
    [3,"trois"],
    [4,"quatre"],
    [5,"cinq"],
    [6,"six"],
    [7,"sept"],
    [8,"huit"],
    [9,"neuf"],
    [10,"dix"],
    [11,"onze"],
    [12,"douze"],
    [13,"treize"],
    [14,"quatorze"],
    [15,"quinze"],
    [16,"seize"],
    [17,"dix-sept"],
    [18,"dix-huit"],
    [19,"dix-neuf"],
    [20,"vingt"],
    [21,"vingt et un"],
    [22,"vingt-deux"],
    [23,"vingt-trois"],
    [24,"vingt-quatre"],
    [25,"vingt-cinq"],
    [26,"vingt-six"],
    [27,"vingt-sept"],
    [28,"vingt-huit"],
    [29,"vingt-neuf"],
    [30,"trente"],
    [31,"trente et un"],
    [32,"trente-deux"],
    [33,"trente-trois"],
    [34,"trente-quatre"],
    [35,"trente-cinq"],
    [36,"trente-six"],
    [37,"trente-sept"],
    [38,"trente-huit"],
    [39,"trente-neuf"],
    [40,"quarante"],
    [41,"quarante et un"],
    [42,"quarante-deux"],
    [43,"quarante-trois"],
    [44,"quarante-quatre"],
    [45,"quarante-cinq"],
    [46,"quarante-six"],
    [47,"quarante-sept"],
    [48,"quarante-huit"],
    [49,"quarante-neuf"],
    [50,"cinquante"],
    [51,"cinquante et un"],
    [52,"cinquante-deux"],
    [53,"cinquante-trois"],
    [54,"cinquante-quatre"],
    [55,"cinquante-cinq"],
    [56,"cinquante-six"],
    [57,"cinquante-sept"],
    [58,"cinquante-huit"],
    [59,"cinquante-neuf"],
    [60,"soixante"],
    [61,"soixante et un"],
    [62,"soixante-deux"],
    [63,"soixante-trois"],
    [64,"soixante-quatre"],
    [65,"soixante-cinq"],
    [66,"soixante-six"],
    [67,"soixante-sept"],
    [68,"soixante-huit"],
    [69,"soixante-neuf"],
    [70,"soixante-dix"],
    [71,"soixante-et-onze"],
    [72,"soixante-douze"],
    [73,"soixante-treize"],
    [74,"soixante-quatorze"],
    [75,"soixante-quinze"],
    [76,"soixante-seize"],
    [77,"soixante-dix-sept"],
    [78,"soixante-dix-huit"],
    [79,"soixante-dix-neuf"],
    [80,"quatre-vingts"],
    [81,"quatre-vingt-un"],
    [82,"quatre-vingt-deux"],
    [83,"quatre-vingt-trois"],
    [84,"quatre-vingt-quatre"],
    [85,"quatre-vingt-cinq"],
    [86,"quatre-vingt-six"],
    [87,"quatre-vingt-sept"],
    [88,"quatre-vingt-huit"],
    [89,"quatre-vingt-neuf"],
    [90,"quatre-vingt-dix"],
    [91,"quatre-vingt-onze"],
    [92,"quatre-vingt-douze"],
    [93,"quatre-vingt-treize"],
    [94,"quatre-vingt-quatorze"],
    [95,"quatre-vingt-quinze"],
    [96,"quatre-vingt-seize"],
    [97,"quatre-vingt-dix-sept"],
    [98,"quatre-vingt-dix-huit"],
    [99,"quatre-vingt-dix-neuf"],
    [100,"cent"]
];

const inverse = [
    ["zéro",0],
    ["un",1],
    ["deux",2],
    ["trois",3],
    ["quatre",4],
    ["cinq",5],
    ["six",6],
    ["sept",7],
    ["huit",8],
    ["neuf",9],
    ["dix",10],
    ["onze",11],
    ["douze",12],
    ["treize",13],
    ["quatorze",14],
    ["quinze",15],
    ["seize",16],
    ["dix-sept",17],
    ["dix-huit",18],
    ["dix-neuf",19],
    ["vingt",20],
    ["vingt et un",21],
    ["vingt-deux",22],
    ["vingt-trois",23],
    ["vingt-quatre",24],
    ["vingt-cinq",25],
    ["vingt-six",26],
    ["vingt-sept",27],
    ["vingt-huit",28],
    ["vingt-neuf",29],
    ["trente",30],
    ["trente et un",31],
    ["trente-deux",32],
    ["trente-trois",33],
    ["trente-quatre",34],
    ["trente-cinq",35],
    ["trente-six",36],
    ["trente-sept",37],
    ["trente-huit",38],
    ["trente-neuf",39],
    ["quarante",40],
    ["quarante et un",41],
    ["quarante-deux",42],
    ["quarante-trois",43],
    ["quarante-quatre",44],
    ["quarante-cinq",45],
    ["quarante-six",46],
    ["quarante-sept",47],
    ["quarante-huit",48],
    ["quarante-neuf",49],
    ["cinquante",50],
    ["cinquante et un",51],
    ["cinquante-deux",52],
    ["cinquante-trois",53],
    ["cinquante-quatre",54],
    ["cinquante-cinq",55],
    ["cinquante-six",56],
    ["cinquante-sept",57],
    ["cinquante-huit",58],
    ["cinquante-neuf",59],
    ["soixante",60],
    ["soixante et un",61],
    ["soixante-deux",62],
    ["soixante-trois",63],
    ["soixante-quatre",64],
    ["soixante-cinq",65],
    ["soixante-six",66],
    ["soixante-sept",67],
    ["soixante-huit",68],
    ["soixante-neuf",69],
    ["soixante-dix",70],
    ["soixante-et-onze",71],
    ["soixante-douze",72],
    ["soixante-treize",73],
    ["soixante-quatorze",74],
    ["soixante-quinze",75],
    ["soixante-seize",76],
    ["soixante-dix-sept",77],
    ["soixante-dix-huit",78],
    ["soixante-dix-neuf",79],
    ["quatre-vingts",80],
    ["quatre-vingt-un",81],
    ["quatre-vingt-deux",82],
    ["quatre-vingt-trois",83],
    ["quatre-vingt-quatre",84],
    ["quatre-vingt-cinq",85],
    ["quatre-vingt-six",86],
    ["quatre-vingt-sept",87],
    ["quatre-vingt-huit",88],
    ["quatre-vingt-neuf",89],
    ["quatre-vingt-dix",90],
    ["quatre-vingt-onze",91],
    ["quatre-vingt-douze",92],
    ["quatre-vingt-treize",93],
    ["quatre-vingt-quatorze",94],
    ["quatre-vingt-quinze",95],
    ["quatre-vingt-seize",96],
    ["quatre-vingt-dix-sept",97],
    ["quatre-vingt-dix-huit",98],
    ["quatre-vingt-dix-neuf",99],
    ["cent",100]
];

const list = [
[0,"zero"],
[1,"one"],
[2,"two"],
[3,"three"],
[4,"four"],
[5,"five"],
[6,"six"],
[7,"seven"],
[8,"eight"],
[9,"nine"],
[10,"ten"],
[11,"eleven"],
[12,"twelve"],
[13,"thirteen"],
[14,"fourteen"],
[15,"fifteen"],
[16,"sixteen"],
[17,"seventeen"],
[18,"eighteen"],
[19,"nineteen"],
[20,"twenty"],
[21,"twenty-one"],
[22,"twenty-two"],
[23,"twenty-three"],
[24,"twenty-four"],
[25,"twenty-five"],
[26,"twenty-six"],
[27,"twenty-seven"],
[28,"twenty-eight"],
[29,"twenty-nine"],
[30,"thirty"],
[31,"thirty-one"],
[32,"thirty-two"],
[33,"thirty-three"],
[34,"thirty-four"],
[35,"thirty-five"],
[36,"thirty-six"],
[37,"thirty-seven"],
[38,"thirty-eight"],
[39,"thirty-nine"],
[40,"forty"],
[41,"forty-one"],
[42,"forty-two"],
[43,"forty-three"],
[44,"forty-four"],
[45,"forty-five"],
[46,"forty-six"],
[47,"forty-seven"],
[48,"forty-eight"],
[49,"forty-nine"],
[50,"fifty"],
[51,"fifty-one"],
[52,"fifty-two"],
[53,"fifty-three"],
[54,"fifty-four"],
[55,"fifty-five"],
[56,"fifty-six"],
[57,"fifty-seven"],
[58,"fifty-eight"],
[59,"fifty-nine"],
[60,"sixty"],
[61,"sixty-one"],
[62,"sixty-two"],
[63,"sixty-three"],
[64,"sixty-four"],
[65,"sixty-five"],
[66,"sixty-six"],
[67,"sixty-seven"],
[68,"sixty-eight"],
[69,"sixty-nine"],
[70,"seventy"],
[71,"seventy-one"],
[72,"seventy-two"],
[73,"seventy-three"],
[74,"seventy-four"],
[75,"seventy-five"],
[76,"seventy-six"],
[77,"seventy-seven"],
[78,"seventy-eight"],
[79,"seventy-nine"],
[80,"eighty"],
[81,"eighty-one"],
[82,"eighty-two"],
[83,"eighty-three"],
[84,"eighty-four"],
[85,"eighty-five"],
[86,"eighty-six"],
[87,"eighty-seven"],
[88,"eighty-eight"],
[89,"eighty-nine"],
[90,"ninety"],
[91,"ninety-one"],
[92,"ninety-two"],
[93,"ninety-three"],
[94,"ninety-four"],
[95,"ninety-five"],
[96,"ninety-six"],
[97,"ninety-seven"],
[98,"ninety-eight"],
[99,"ninety-nine"],
[100,"hundred"]
];

const reverse = [
["zero",0],
["one",1],
["two",2],
["three",3],
["four",4],
["five",5],
["six",6],
["seven",7],
["eight",8],
["nine",9],
["ten",10],
["eleven",11],
["twelve",12],
["thirteen",13],
["fourteen",14],
["fifteen",15],
["sixteen",16],
["seventeen",17],
["eighteen",18],
["nineteen",19],
["twenty",20],
["twenty-one",21],
["twenty-two",22],
["twenty-three",23],
["twenty-four",24],
["twenty-five",25],
["twenty-six",26],
["twenty-seven",27],
["twenty-eight",28],
["twenty-nine",29],
["thirty",30],
["thirty-one",31],
["thirty-two",32],
["thirty-three",33],
["thirty-four",34],
["thirty-five",35],
["thirty-six",36],
["thirty-seven",37],
["thirty-eight",38],
["thirty-nine",39],
["forty",40],
["forty-one",41],
["forty-two",42],
["forty-three",43],
["forty-four",44],
["forty-five",45],
["forty-six",46],
["forty-seven",47],
["forty-eight",48],
["forty-nine",49],
["fifty",50],
["fifty-one",51],
["fifty-two",52],
["fifty-three",53],
["fifty-four",54],
["fifty-five",55],
["fifty-six",56],
["fifty-seven",57],
["fifty-eight",58],
["fifty-nine",59],
["sixty",60],
["sixty-one",61],
["sixty-two",62],
["sixty-three",63],
["sixty-four",64],
["sixty-five",65],
["sixty-six",66],
["sixty-seven",67],
["sixty-eight",68],
["sixty-nine",69],
["seventy",70],
["seventy-one",71],
["seventy-two",72],
["seventy-three",73],
["seventy-four",74],
["seventy-five",75],
["seventy-six",76],
["seventy-seven",77],
["seventy-eight",78],
["seventy-nine",79],
["eighty",80],
["eighty-one",81],
["eighty-two",82],
["eighty-three",83],
["eighty-four",84],
["eighty-five",85],
["eighty-six",86],
["eighty-seven",87],
["eighty-eight",88],
["eighty-nine",89],
["ninety",90],
["ninety-one",91],
["ninety-two",92],
["ninety-three",93],
["ninety-four",94],
["ninety-five",95],
["ninety-six",96],
["ninety-seven",97],
["ninety-eight",98],
["ninety-nine",99],
["hundred",100]
];


const chiffres = new Map(liste);
const chiffreLettre = envoi => chiffres.has(envoi) ? chiffres.get(envoi) : chiffres.get(0);

const lettres = new Map(inverse);
const lettreChiffre = envoi => lettres.has(envoi) ? lettres.get(envoi) : lettres.get("zéro");

const chiffresAnglais = new Map(list);
const chiffreLettreAnglais = envoi => chiffresAnglais.has(envoi) ? chiffresAnglais.get(envoi) : chiffresAnglais.get(0);

const lettresAnglaises = new Map(reverse);
const lettreChiffreAnglais = envoi => lettresAnglaises.has(envoi) ? lettresAnglaises.get(envoi) : lettresAnglaises.get("zéro");

//module.exports = {chiffreLettre, lettreChiffre};
export {chiffreLettre, lettreChiffre};
