// https://fr.wikipedia.org/wiki/Champions_olympiques_fran%C3%A7ai

export default  [
    {nom:"Martin Fourcade", booleen:true},
    {nom:"Lucien Gaudin", booleen:true},
    {nom:"Christian d’Oriola", booleen:true},
    {nom:"Marie-José Pérec", booleen:true},
    {nom:"Tony Estanguet", booleen:true},
    {nom:"Félicia Ballanger", booleen:true},
    {nom:"Paul Masson", booleen:true},
    {nom:"Daniel Morelon", booleen:true},
    {nom:"Florian Rousseau", booleen:true},
    {nom:"Robert Charpentier", booleen:true},
    {nom:"Jéhan de Buhan", booleen:true},
    {nom:"Philippe Cattiau", booleen:true},
    {nom:"Roger Ducret", booleen:true},
    {nom:"Luc Abalo", booleen:true},
    {nom:"Michaël Guigou", booleen:true},
    {nom:"Nikola Karabatic", booleen:true},
    {nom:"Teddy Riner", booleen:true},
    {nom:"Jean-Claude Killy", booleen:true},

    {nom:"Michel Théato", booleen:true},
    {nom:"Joseph Guillemot", booleen:true},
    {nom:"Boughéra El Ouafi", booleen:true},
    {nom:"Micheline Ostermeyer", booleen:true},
    {nom:"Alain Mimoun", booleen:true},
    {nom:"Colette Besson", booleen:true},
    {nom:"Guy Drut", booleen:true},
    {nom:"Pierre Quinon", booleen:true},
    {nom:"Marie-José Pérec", booleen:true},
    {nom:"Jean Galfione", booleen:true},
    {nom:"Renaud Lavillenie", booleen:true},

    {nom:"Émile Delchambre", booleen:true},
    {nom:"Henri Bouckaert", booleen:true},
    {nom:"Henri Hazebrouck", booleen:true},
    {nom:"Jean Cau", booleen:true},
    {nom:"Charlot", booleen:true},
    {nom:"Henri Barrelet", booleen:true},
    {nom:"Bernard Malivoire", booleen:true},
    {nom:"Gaston Mercier", booleen:true},
    {nom:"Raymond Salles", booleen:true},
    {nom:"Jean-Christophe Rolland", booleen:true},
    {nom:"Michel Andrieux", booleen:true},
    {nom:"Jean-Christophe Bette", booleen:true},
    {nom:"Laurent Porchier", booleen:true},
    {nom:"Xavier Dorfman", booleen:true},
    {nom:"Yves Hocdé", booleen:true},
    {nom:"Adrien Hardy", booleen:true},
    {nom:"Sébastien Vieilledent", booleen:true},
    {nom:"Jérémie Azou", booleen:true},
    {nom:"Pierre Houin", booleen:true},
    {nom:"Matthieu Androdias", booleen:true},
    {nom:"Hugo Boucheron", booleen:true},

    {nom:"Paul Fritsch", booleen:true},
    {nom:"Jean Despeaux", booleen:true},
    {nom:"Roger Michelot", booleen:true},
    {nom:"Brahim Asloum", booleen:true},
    {nom:"Estelle Mossely", booleen:true},
    {nom:"Tony Yoka", booleen:true},

    {nom:"Georges Turlier", booleen:true},
    {nom:"Jean Laudet", booleen:true},
    {nom:"Franck Adisson", booleen:true},
    {nom:"Wilfrid Forgues", booleen:true},
    {nom:"Tony Estanguet", booleen:true},
    {nom:"Benoît Peschier", booleen:true},
    {nom:"Émilie Fer", booleen:true},
    {nom:"Denis Gargaud Chanut", booleen:true},

    {nom:"Anne-Caroline Chausson", booleen:true},

    {nom:"Léon Flameng", booleen:true},
    {nom:"Paul Masson", booleen:true},
    {nom:"Georges Taillandier", booleen:true},
    {nom:"Louis Bastien", booleen:true},
    {nom:"André Auffray", booleen:true},
    {nom:"Maurice Schilles", booleen:true},
    {nom:"Lucien Michard", booleen:true},
    {nom:"Jean Cugnot", booleen:true},
    {nom:"Lucien Choury", booleen:true},
    {nom:"Roger Beaufrand", booleen:true},
    {nom:"Louis Chaillot", booleen:true},
    {nom:"Maurice Perrin", booleen:true},
    {nom:"Jean Goujon", booleen:true},
    {nom:"Roger Le Nizerhy", booleen:true},
    {nom:"Jacques Dupont", booleen:true},
    {nom:"Charles Coste", booleen:true},
    {nom:"Fernand Decanali", booleen:true},
    {nom:"Pierre Adam", booleen:true},
    {nom:"Serge Blusson", booleen:true},
    {nom:"Michel Rousseau", booleen:true},
    {nom:"Pierre Trentin", booleen:true},
    {nom:"Daniel Morelon", booleen:true},
    {nom:"Daniel Rebillard", booleen:true},
    {nom:"Christophe Capelle", booleen:true},
    {nom:"Francis Moreau", booleen:true},
    {nom:"Jean-Michel Monin", booleen:true},
    {nom:"Philippe Ermenault", booleen:true},
    {nom:"Félicia Ballanger", booleen:true},
    {nom:"Florian Rousseau", booleen:true},
    {nom:"Nathalie Even", booleen:true},
    {nom:"Arnaud Tournant", booleen:true},
    {nom:"Laurent Gané", booleen:true},

    {nom:"Achille Souchard", booleen:true},
    {nom:"Fernand Canteloube", booleen:true},
    {nom:"Georges Detreille", booleen:true},
    {nom:"Marcel Gobillot", booleen:true},
    {nom:"Armand Blanchonnet", booleen:true},
    {nom:"Georges Wambst", booleen:true},
    {nom:"René Hamel", booleen:true},
    {nom:"Robert Charpentier", booleen:true},
    {nom:"Guy Lapébie", booleen:true},
    {nom:"Robert Dorgebray", booleen:true},
    {nom:"José Beyaert", booleen:true},
    {nom:"Arnaud Geyre", booleen:true},
    {nom:"Maurice Moucheraud", booleen:true},
    {nom:"Michel Vermeulin", booleen:true},
    {nom:"Jeannie Longo-Ciprelli", booleen:true},

    {nom:"Miguel Martinez", booleen:true},
    {nom:"Julien Absalon", booleen:true},
    {nom:"Julie Bresset", booleen:true},

    {nom:"Dominique Maximien Gardères", booleen:true},
    {nom:"Jacques Cariou", booleen:true},
    {nom:"Xavier Lesage", booleen:true},
    {nom:"André Jousseaume", booleen:true},
    {nom:"Charles Marion", booleen:true},
    {nom:"Bernard Chevallier", booleen:true},
    {nom:"Maurice Buret", booleen:true},
    {nom:"Jean Saint-Fort-Paillard", booleen:true},
    {nom:"Pierre Jonquères d’Oriola", booleen:true},
    {nom:"Jean-Jacques Guyon", booleen:true},
    {nom:"Hubert Parot", booleen:true},
    {nom:"Marc Roguet", booleen:true},
    {nom:"Marcel Rozier", booleen:true},
    {nom:"Michel Roche", booleen:true},
    {nom:"Pierre Durand", booleen:true},
    {nom:"Arnaud Boiteau", booleen:true},
    {nom:"Cédric Lyard", booleen:true},
    {nom:"Didier Courrèges", booleen:true},
    {nom:"Jean Teulère", booleen:true},
    {nom:"Nicolas Touzaint", booleen:true},
    {nom:"Karim Laghouag", booleen:true},
    {nom:"Thibaut Vallette", booleen:true},
    {nom:"Mathieu Lemoine", booleen:true},
    {nom:"Astier Nicolas", booleen:true},
    {nom:"Roger-Yves Bost", booleen:true},
    {nom:"Philippe Rozier", booleen:true},
    {nom:"Kevin Staut", booleen:true},
    {nom:"Pénélope Leprevost", booleen:true},

    {nom:"Eugène-Henri Gravelotte", booleen:true},
    {nom:"Albert Ayat", booleen:true},
    {nom:"Émile Coste", booleen:true},
    {nom:"Lucien Mérignac", booleen:true},
    {nom:"Georges de La Falaise", booleen:true},
    {nom:"Gaston Alibert", booleen:true},
    {nom:"Herman Georges Berger", booleen:true},
    {nom:"Charles Collignon", booleen:true},
    {nom:"Bernard Gravier", booleen:true},
    {nom:"Alexandre Lippmann", booleen:true},
    {nom:"Eugène Olivier", booleen:true},
    {nom:"Jean Stern", booleen:true},
    {nom:"Armand Massard", booleen:true},
    {nom:"Roger Ducret", booleen:true},
    {nom:"Georges Buchard", booleen:true},
    {nom:"Lucien Gaudin", booleen:true},
    {nom:"André Labatut", booleen:true},
    {nom:"Lionel Liottel", booleen:true},
    {nom:"Georges Tainturier", booleen:true},
    {nom:"Philippe Cattiau", booleen:true},
    {nom:"Jacques Coutrot", booleen:true},
    {nom:"Henri Jobier", booleen:true},
    {nom:"Guy de Luget", booleen:true},
    {nom:"Joseph Perotaux", booleen:true},
    {nom:"Fernand Jourdant", booleen:true},
    {nom:"Jean Piot", booleen:true},
    {nom:"Bernard Schmetz", booleen:true},
    {nom:"René Bondoux", booleen:true},
    {nom:"René Bougnol", booleen:true},
    {nom:"Edward Gardère", booleen:true},
    {nom:"René Lemoine", booleen:true},
    {nom:"Jéhan de Buhan", booleen:true},
    {nom:"Édouard Artigas", booleen:true},
    {nom:"Marcel Desprets", booleen:true},
    {nom:"Henri Guérin", booleen:true},
    {nom:"Maurice Huet", booleen:true},
    {nom:"Henri Lepage", booleen:true},
    {nom:"Michel Pécheux", booleen:true},
    {nom:"André Bonin", booleen:true},
    {nom:"Christian d’Oriola", booleen:true},
    {nom:"Jacques Lataste", booleen:true},
    {nom:"Adrien Rommel", booleen:true},
    {nom:"Claude Netter", booleen:true},
    {nom:"Jacques Noël", booleen:true},
    {nom:"Gilles Berolatti", booleen:true},
    {nom:"Jacques Dimont", booleen:true},
    {nom:"Jean-Claude Magnan", booleen:true},
    {nom:"Christian Noël", booleen:true},
    {nom:"Daniel Revenu", booleen:true},
    {nom:"Pascale Trinquet", booleen:true},
    {nom:"Philippe Boisse", booleen:true},
    {nom:"Hubert Gardas", booleen:true},
    {nom:"Patrick Picot", booleen:true},
    {nom:"Philippe Riboud", booleen:true},
    {nom:"Michel Salesse", booleen:true},
    {nom:"Philippe Bonnin", booleen:true},
    {nom:"Bruno Boscherie", booleen:true},
    {nom:"Didier Flament", booleen:true},
    {nom:"Pascal Jolyot", booleen:true},
    {nom:"Frédéric Pietruszka", booleen:true},
    {nom:"Isabelle Boéri", booleen:true},
    {nom:"Véronique Brouquier", booleen:true},
    {nom:"Brigitte Gaudin", booleen:true},
    {nom:"Christine Muzio", booleen:true},
    {nom:"Jean-François Lamour", booleen:true},
    {nom:"Frédéric Delpla", booleen:true},
    {nom:"Jean-Michel Henry", booleen:true},
    {nom:"Olivier Lenglet", booleen:true},
    {nom:"Éric Srecki", booleen:true},
    {nom:"Philippe Omnès", booleen:true},
    {nom:"Laura Flessel", booleen:true},
    {nom:"Valérie Barlois", booleen:true},
    {nom:"Sophie Moressée-Pichot", booleen:true},
    {nom:"Jean-Noël Ferrari", booleen:true},
    {nom:"Brice Guyart", booleen:true},
    {nom:"Patrice Lhôtellier", booleen:true},
    {nom:"Lionel Plumenail", booleen:true},
    {nom:"Érik Boisse", booleen:true},
    {nom:"Fabrice Jeannet", booleen:true},
    {nom:"Jérôme Jeannet", booleen:true},
    {nom:"Hugues Obry", booleen:true},
    {nom:"Damien Touya", booleen:true},
    {nom:"Gaël Touya", booleen:true},
    {nom:"Julien Pillet", booleen:true},
    {nom:"Ulrich Robeiri", booleen:true},
    {nom:"Nicolas Lopez", booleen:true},
    {nom:"Boris Sanson", booleen:true},
    {nom:"Yannick Borel", booleen:true},
    {nom:"Gauthier Grumier", booleen:true},
    {nom:"Daniel Jérent", booleen:true},
    {nom:"Jean-Michel Lucenay", booleen:true},
    {nom:"Romain Cannone", booleen:true},
    {nom:"Enzo Lefort", booleen:true},
    {nom:"Erwann Le Péchoux", booleen:true},
    {nom:"Julien Mertine", booleen:true},
    {nom:"Maxime Pauty", booleen:true},

    {nom:"William Ayache", booleen:true},
    {nom:"Michel Bensoussan", booleen:true},
    {nom:"Michel Bibard", booleen:true},
    {nom:"Dominique Bijotat", booleen:true},
    {nom:"François Brisson", booleen:true},
    {nom:"Patrick Cubaynes", booleen:true},
    {nom:"Patrice Garande", booleen:true},
    {nom:"Philippe Jeannol", booleen:true},
    {nom:"Guy Lacombe", booleen:true},
    {nom:"Jean-Claude Lemoult", booleen:true},
    {nom:"Jean-Philippe Rohr", booleen:true},
    {nom:"Albert Rust", booleen:true},
    {nom:"Didier Sénac", booleen:true},
    {nom:"Jean-Christophe Thouvenel", booleen:true},
    {nom:"José Touré", booleen:true},
    {nom:"Daniel Xuereb", booleen:true},
    {nom:"Jean-Louis Zanon", booleen:true},

    {nom:"Gustave Sandras", booleen:true},
    {nom:"Albert Séguin", booleen:true},
    {nom:"Émilie Le Pennec", booleen:true},

    {nom:"Henri Gance", booleen:true},
    {nom:"Ernest Cadine", booleen:true},
    {nom:"Edmond Decottignies", booleen:true},
    {nom:"Charles Rigoulot", booleen:true},
    {nom:"Roger François", booleen:true},
    {nom:"Raymond Suvigny", booleen:true},
    {nom:"René Duverger", booleen:true},
    {nom:"Louis Hostin", booleen:true},

    {nom:"Luc Abalo", booleen:true},
    {nom:"Michaël Guigou", booleen:true},
    {nom:"Nikola Karabatic", booleen:true},
    {nom:"Didier Dinart", booleen:true},
    {nom:"Jérôme Fernandez", booleen:true},
    {nom:"Bertrand Gille", booleen:true},
    {nom:"Guillaume Gille", booleen:true},
    {nom:"Daouda Karaboué", booleen:true},
    {nom:"Daniel Narcisse", booleen:true},
    {nom:"Thierry Omeyer", booleen:true},
    {nom:"Joël Abati", booleen:true},
    {nom:"Cédric Burdet", booleen:true},
    {nom:"Olivier Girault", booleen:true},
    {nom:"Christophe Kempé", booleen:true},
    {nom:"Cédric Paty", booleen:true},
    {nom:"William Accambray", booleen:true},
    {nom:"Xavier Barachet", booleen:true},
    {nom:"Samuel Honrubia", booleen:true},
    {nom:"Guillaume Joli", booleen:true},
    {nom:"Cédric Sorhaindo", booleen:true},
    {nom:"Rémi Desbonnet", booleen:true},
    {nom:"Hugo Descat", booleen:true},
    {nom:"Ludovic Fabregas", booleen:true},
    {nom:"Yann Genty", booleen:true},
    {nom:"Vincent Gérard", booleen:true},
    {nom:"Luka Karabatic", booleen:true},
    {nom:"Romain Lagarde", booleen:true},
    {nom:"Kentin Mahé", booleen:true},
    {nom:"Dika Mem", booleen:true},
    {nom:"Timothey N’Guessan", booleen:true},
    {nom:"Valentin Porte", booleen:true},
    {nom:"Nedim Remili", booleen:true},
    {nom:"Melvyn Richardson", booleen:true},
    {nom:"Nicolas Tournat", booleen:true},
    {nom:"Pauline Coatanea", booleen:true},
    {nom:"Blandine Dancette", booleen:true},
    {nom:"Cléopatre Darleux", booleen:true},
    {nom:"Béatrice Edwige", booleen:true},
    {nom:"Laura Flippes", booleen:true},
    {nom:"Pauletta Foppa", booleen:true},
    {nom:"Alexandra Lacrabère", booleen:true},
    {nom:"Coralie Lassource", booleen:true},
    {nom:"Amandine Leynaud", booleen:true},
    {nom:"Kalidiatou Niakaté", booleen:true},
    {nom:"Méline Nocandy", booleen:true},
    {nom:"Estelle Nze Minko", booleen:true},
    {nom:"Allison Pineau", booleen:true},
    {nom:"Océane Sercien-Ugolin", booleen:true},
    {nom:"Chloé Valentini", booleen:true},
    {nom:"Grâce Zaadi", booleen:true},

    {nom:"Angelo Parisi", booleen:true},
    {nom:"Thierry Rey", booleen:true},
    {nom:"Marc Alexandre", booleen:true},
    {nom:"Cécile Nowak", booleen:true},
    {nom:"Catherine Fleury", booleen:true},
    {nom:"David Douillet", booleen:true},
    {nom:"Marie-Claire Restoux", booleen:true},
    {nom:"Djamel Bouras", booleen:true},
    {nom:"Séverine Vandenhende", booleen:true},
    {nom:"Lucie Décosse", booleen:true},
    {nom:"Teddy Riner", booleen:true},
    {nom:"Émilie Andéol", booleen:true},
    {nom:"Clarisse Agbégnénou", booleen:true},
    {nom:"Axel Clerget", booleen:true},
    {nom:"Romane Dicko", booleen:true},
    {nom:"Sarah-Léonie Cysique", booleen:true},
    {nom:"Guillaume Chaine", booleen:true},

    {nom:"Steven Da Costa", booleen:true},

    {nom:"Henri Deglane", booleen:true},
    {nom:"Charles Pacôme", booleen:true},
    {nom:"Émile Poilvé", booleen:true},
    {nom:"Steeve Guénot", booleen:true},

    {nom:"Charles Devendeville", booleen:true},
    {nom:"Jean Boiteux", booleen:true},
    {nom:"Laure Manaudou", booleen:true},
    {nom:"Alain Bernard", booleen:true},
    {nom:"Camille Muffat", booleen:true},
    {nom:"Fabien Gilot", booleen:true},
    {nom:"Clément Lefert", booleen:true},
    {nom:"Amaury Leveaux", booleen:true},
    {nom:"Jérémy Stravius", booleen:true},
    {nom:"Florent Manaudou", booleen:true},

    {nom:"André Gobert", booleen:true},
    {nom:"Maurice Germot", booleen:true},
    {nom:"Marguerite Broquedis", booleen:true},
    {nom:"Max Decugis", booleen:true},
    {nom:"Suzanne Lenglen", booleen:true},

    {nom:"Roger de Barbarin", booleen:true},
    {nom:"Achille Paroche", booleen:true},
    {nom:"Maurice Larrouy", booleen:true},
    {nom:"Paul Colas", booleen:true},
    {nom:"Pierre Coquelin de Lisle", booleen:true},
    {nom:"Philippe Heberlé", booleen:true},
    {nom:"Jean-Pierre Amat", booleen:true},
    {nom:"Franck Dumoulin", booleen:true},
    {nom:"Jean Quiquampoix", booleen:true},

    {nom:"Eugène Mougin", booleen:true},
    {nom:"Henri Hérouin", booleen:true},
    {nom:"Émile Grumiaux", booleen:true},
    {nom:"Eugène Grisot", booleen:true},
    {nom:"Julien Brulé", booleen:true},
    {nom:"Sébastien Flute", booleen:true},

    {nom:"Pierre Gervais", booleen:true},
    {nom:"Émile Sacré", booleen:true},
    {nom:"Emile Billard", booleen:true},
    {nom:"Paul Perquer", booleen:true},
    {nom:"Amédée Thubé", booleen:true},
    {nom:"Gaston Thubé", booleen:true},
    {nom:"Jacques Thubé", booleen:true},
    {nom:"André Derrien", booleen:true},
    {nom:"André Lesauvage", booleen:true},
    {nom:"Carl de la Sablière", booleen:true},
    {nom:"Donatien Bouché", booleen:true},
    {nom:"Jean Lesieur", booleen:true},
    {nom:"Virginie Hériot", booleen:true},
    {nom:"Jacques Lebrun", booleen:true},
    {nom:"Serge Maury", booleen:true},
    {nom:"Thierry Péponnet", booleen:true},
    {nom:"Luc Pillot", booleen:true},
    {nom:"Nicolas Hénard", booleen:true},
    {nom:"Jean-Yves Le Déroff", booleen:true},
    {nom:"Franck David", booleen:true},
    {nom:"Yves Loday", booleen:true},
    {nom:"Faustine Merret", booleen:true},
    {nom:"Charline Picon", booleen:true},

    {nom:"Stephen Boyer", booleen:true},
    {nom:"Antoine Brizard", booleen:true},
    {nom:"Daryl Bultor", booleen:true},
    {nom:"Barthélémy Chinenyeze", booleen:true},
    {nom:"Trévor Clévenot", booleen:true},
    {nom:"Jenia Grebennikov", booleen:true},
    {nom:"Nicolas Le Goff", booleen:true},
    {nom:"Yacine Louati", booleen:true},
    {nom:"Earvin Ngapeth", booleen:true},
    {nom:"Jean Patry", booleen:true},
    {nom:"Kévin Tillie", booleen:true},
    {nom:"Benjamin Toniutti", booleen:true},

    {nom:"Albert Deborgies", booleen:true},
    {nom:"Albert Mayaud", booleen:true},
    {nom:"Georges Rigal", booleen:true},
    {nom:"Henri Padou", booleen:true},
    {nom:"Noël Delberghe", booleen:true},
    {nom:"Paul Dujardin", booleen:true},
    {nom:"Robert Desmettre", booleen:true},

    {nom:"Anne Briand", booleen:true},
    {nom:"Véronique Claudel", booleen:true},
    {nom:"Corinne Niogret", booleen:true},
    {nom:"Florence Baverel-Robert", booleen:true},
    {nom:"Vincent Defrasne", booleen:true},
    {nom:"Vincent Jay", booleen:true},
    {nom:"Martin Fourcade", booleen:true},
    {nom:"Anaïs Bescond", booleen:true},
    {nom:"Simon Desthieux", booleen:true},
    {nom:"Marie Dorin-Habert", booleen:true},

    {nom:"Fabrice Guy", booleen:true},
    {nom:"Jason Lamy-Chappuis", booleen:true},

    {nom:"Pierre Brunet", booleen:true},
    {nom:"Andrée Joly", booleen:true},
    {nom:"Marina Anissina", booleen:true},
    {nom:"Gwendal Peizerat", booleen:true},

    {nom:"Edgar Grospiron", booleen:true},
    {nom:"Jean-Frédéric Chapuis", booleen:true},
    {nom:"Perrine Laffont", booleen:true},

    {nom:"Henri Oreiller", booleen:true},

    {nom:"Jean Vuarnet", booleen:true},
    {nom:"Christine Goitschel", booleen:true},
    {nom:"Marielle Goitschel", booleen:true},
    {nom:"François Bonlieu", booleen:true},
    {nom:"Jean-Claude Killy", booleen:true},
    {nom:"Franck Piccard", booleen:true},
    {nom:"Jean-Luc Crétier", booleen:true},
    {nom:"Carole Montillet", booleen:true},
    {nom:"Jean-Pierre Vidal", booleen:true},
    {nom:"Antoine Dénériaz", booleen:true},

    {nom:"Karine Ruby", booleen:true},
    {nom:"Isabelle Blanc", booleen:true},
    {nom:"Pierre Vaultier", booleen:true},
];
