//iso2 ISO 3166-1 alpha-2
//iso2 ISO 3166-1 alpha-3
//insee.fr/fr/information/2028273

const iso3Villes = [
    ["fra", ["Paris","Marseille","Lyon","Toulouse","Nice","Nantes","Montpellier","Strasbourg","Bordeaux","Lille"]],
    ["dnk", ["Copenhague","Aarhus","Aalborg","Odense","Esbjerg","Vejle","Randers","Viborg","Kolding","Silkeborg"]],
    ["fro", ["Tórshavn","Klaksvík","Runavík","Eystur","Vága","Tvøroyri","Fuglafjørður","Sunda","Vágur","Nes"]],
    ["isl", ["Reykjavik", "Akureyri", "Keflavík"]],
    ["bvt", ["Île Bouvet"]],
    ["nor", ["Oslo","Bergen","Stavanger", "Sandvika", "Sandnes","Trondheim","Fredrikstad",  "Drammen", "Kristiansand","Tromsø"]],
    ["sjm", ["Svalbard", "Île Jan Mayen"]],
    ["swe", ["Stockholm","Göteborg","Malmö","Uppsala","Västerås","Örebro","Linköping","Helsingborg","Jönköping","Norrköping"]],
    ["fin", ["Helsinki","Espoo","Tampere","Vantaa","Oulu","Turku","Jyväskylä","Lahti","Kuopio","Pori"]],
    ["est", ["Tallinn","Tartu","Narva","Kohtla-Järve","Pärnu","Viljandi","Rakvere","Maardu","Sillamäe","Kuressaare"]],
    ["lva", ["Riga","Daugavpils","Liepāja","Jelgava","Jūrmala","Ventspils","Rēzekne","Jēkabpils","Valmiera","Ogre"]],
    ["ltu", ["Vilnius","Kaunas","Klaipėda","Šiauliai","Panevėžys","Alytus","Marijampolė","Mažeikiai","Jonava","Utena"]],
    ["deu", ["Berlin","Hambourg","Munich","Cologne","Francfort-sur-le-Main","Stuttgart","Düsseldorf","Leipzig","Dortmund","Essen"]],
    ["aut", ["Vienne","Graz","Linz","Salzbourg","Innsbruck","Klagenfurt","Villach","Wels","Sankt Pölten","Dornbirn"]],
    ["bgr", ["Sofia","Plovdiv","Varna","Burgas","Ruse","Stara Zagora","Pleven","Sliven","Dobrich","Shumen"]],
    ["hun", ["Budapest","Debrecen","Miskolc","Szeged","Pécs","Győr","Nyíregyháza","Kecskemét","Székesfehérvár","Szombathely"]],
    ["lie", ["Vaduz", "Schaan"]],
    ["rou", ["Bucarest","Cluj","Timișoara","Iași","Constanța","Craiova","Brașov","Galați","Ploiești","Oradea"]],
    ["cze", ["Prague","Brno","Ostrava","Pilsen","Liberec","Olomouc","České Budějovice","Ústí nad Labem","Hradec Králové","Pardubice"]],
    ["svk", ["Bratislava","Košice","Prešov","Nitra","Žilina","Banská Bystrica","Trnava","Martin","Trenčín","Poprad"]],
    ["bih", ["Sarajevo","Banja Luka","Tuzla","Zenica","Bijeljina","Mostar","Prijedor","Brčko","Doboj","Cazin"]],
    ["hrv", ["Zagreb","Split","Rijeka","Osijek","Zadar","Slavonski Brod","Velika Gorica","Karlovac","Pula","Sisak"]],
    ["mne", ["Podgorica","Nikšić","Bijelo Polje","Bar","Berane","Herceg Novi","Pljevlja","Rožaje","Kotor","Budva"]],
    ["srb", ["Belgrade","Novi Sad","Niš","Kragujevac","Leskovac","Subotica","Zrenjanin","Pančevo","Čačak","Kraljevo"]],
    ["pol", ["Varsovie","Cracovie","Łódź","Wrocław","Poznań","Gdańsk","Szczecin","Bydgoszcz","Lublin","Katowice"]],
    ["rus", ["Moscou","Saint-Pétersbourg","Novossibirsk","Iekaterinbourg","Nijni Novgorod","Kazan","Samara","Tcheliabinsk","Omsk","Rostov-sur-le-Don"]],
    ["alb", ["Tirana","Elbasan","Shkodra","Fier","Durrës","Vlora","Kamza","Korça","Lezha","Pogradec"]],
    ["grc", ["Athènes","Thessalonique","Patras","Le Pirée","Larissa","Héraklion","Peristéri","Kallithéa","Acharnes","Kalamariá"]],
    ["ita", ["Rome","Milan","Naples","Turin","Palerme","Gênes","Bologne","Florence","Bari","Catane"]],
    ["smr", ["Saint-Marin","Acquaviva","Borgo Maggiore","Chiesanuova","Domagnano","Faetano","Fiorentino","Montegiardino","Serravalle"]],
    ["vat", ["Vatican"]],
    ["and", ["Canillo","Encamp","Ordino","La Massana","Andorre-la-Vieille","Sant Julià de Lòria","Escaldes-Engordany"]],
    ["bel", ["Anvers","Gand","Charleroi","Liège","Bruxelles","Bruges","Namur","Louvain","Mons","Malines"]],
    ["ggy", ["Saint-Pierre-Port","Le Valle","Sainte-Marie-du-Câtel","Saint-Samson","Saint-Martin-de-la-Bellouse","Saint-Sauveur","Saint-André-de-la-Pommeraye","Saint-Pierre-du-Bois","La Forêt","Torteval"]],
    ["jey", ["Saint-Hélier","Grouville","Saint-Brélade","Saint-Clément","Saint-Jean","Saint-Laurent","Saint-Martin","Saint-Marie","Saint-Ouen","Saint-Pierre","Saint-Sauveur","Trinity"]],
    ["imn", ["Douglas","Ramsey","Peel","Castletown","Onchan","Port Erin","Port St Mary","Laxey"]],
    ["gbr", ["Londres","Birmingham","Glasgow","Manchester","Édimbourg","Liverpool","Leeds","Bristol","Sheffield","Newcastle upon Tyne"]],
    ["gib", ["Gibraltar"]],
    ["esp", ["Madrid","Barcelone","Valence","Séville","Saragosse","Malaga","Murcie","Palma de Majorque","Las Palmas de Gran Canaria","Bilbao"]],
    ["abw", ["Oranjestad","Noord","Paradera","San Nicolaas","Santa Cruz","Savaneta"]],
    ["nld", ["Amsterdam","Rotterdam","The Hague","Utrecht","Eindhoven","Groningen","Tilburg","Almere","Breda","Nijmegen"]],
    ["irl", ["Dublin","Cork","Limerick","Galway","Waterford","Drogheda","Swords","Dundalk","Bray","Navan"]],
    ["lux", ["Luxembourg","Esch-sur-Alzette","Differdange","Dudelange","Ettelbruck","Diekirch","Wiltz","Echternach","Rumelange","Grevenmacher"]],
    ["mco", ["Monaco"]],
    ["prt", ["Lisbonne","Porto","Vila Nova de Gaia","Amadora","Braga","Funchal","Coimbra","Almada","Barreiro","Setúbal"]],
    ["che", ["Zurich","Genève","Bâle","Lausanne","Berne","Winterthour","Lucerne","Saint-Gall","Lugano","Bienne"]],
    ["mlt", ["La Valette"]],
    ["svn", ["Ljubljana","Maribor","Kranj","Koper","Celje","Novo Mesto","Domžale","Velenje","Nova Gorica","Kamnik"]],
    ["blr", ["Minsk","Homiel","Mahiliow","Vitsiebsk","Hrodna","Brest","Babrouïsk","Baranavitchy","Baryssaw","Pinsk"]],
    ["mda", ["Chișinău","Tiraspol","Bălți","Tighina","Rîbnița","Cahul","Ocnița","Ungheni","Soroca","Orhei","Dubăsari"]],
    ["ukr", ["Kiev","Kharkiv","Dnipro","Odessa","Donetsk","Zaporijia","Lviv","Kryvyï Rih","Mykolaïv","Marioupol"]],
    ["mkd", ["Bitola","Gostivar","Koumanovo","Ohrid","Prilep","Skopje","Strouga","Stroumitsa","Tetovo","Vélès"]],
    ["xxk", ["Prishtinë","Prizren","Ferizaj","Pejë","Gjakovë","Gjilan","Podujevë","Mitrovicë","Vushtrri","Suharekë"]],
    ["sau", ["Riyad","Djeddah","La Mecque","Médine","Dammam","Taëf","Tabuk","Buraydah","Khamis Mushait","Al-Hufuf"]],
    ["irq", ["Bagdad","Bassorah","Mossoul","Arbil","Souleimaniye","Kirkuk","Nadjaf","Kerbela","Nassiriya","Amara"]],
    ["irn", ["Téhéran","Mechhed","Ispahan","Tabriz","Karadj","Chiraz","Ahvaz","Qom","Kermanchah","Ourmia"]],
    ["lbn", ["Beyrouth","Tripoli","Sidon","Tyr","Nabatieh","Jounieh","Zahlé","Baabda","Zgharta","Baalbek"]],
    ["syr", ["Alep","Damas","Homs","Lattaquié","Hama","Rakka","Deir ez-Zor","Hassaké","Qamichli","Yarmouk"]],
    ["isr", ["Jérusalem","Tel-Aviv-Jaffa","Haïfa","Rishon LeZion","Petah Tikva","Ashdod","Beer-Sheva","Holon","Netanya","Bnei Brak"]],
    ["tur", ["Istanbul","Ankara","Izmir","Bursa","Adana","Gaziantep","Konya","Antalya","Kayseri","Mersin"]],
    ["afg", ["Kaboul","Hérat","Kandahâr","Mazar-e-Charif","Jalalabad","Kondôz","Khost","Pol-e Khomri","Maimana","Sheberghan"]],
    ["pak", ["Karachi","Lahore","Faisalabad","Rawalpindi","Gujranwala","Peshawar","Multan","Hyderabad","Islamabad","Quetta"]],
    ["btn", ["Thimphou","Phuentsholing","Geylegphug","Wangdue","Samdrup Jongkhar","Samtse","Gedu","Bumthang","Gomtu","Mongar"]],
    ["npl", ["Katmandou","Pokhara","Lalitpur","Biratnagar","Bharatpur","Birganj","Butwal","Dharan","Bhimdatta","Dhangadhi"]],
    ["chn", ["Shanghai","Pékin","Canton","Shenzhen","Dongguan","Tianjin","Wuhan","Shenyang","Nankin","Chongqing","Chengdu","Hangzhou","Xi’an","Qingdao","Harbin","Changchun","Changsha","Nanchang","Shijiazhuang","Dalian","Jinan"]],
    ["hk", ["Hong Kong"]],
    ["jpn", ["Tokyo","Yokohama","Ōsaka","Nagoya","Sapporo","Kōbe","Fukuoka","Kawasaki","Kyōto","Saitama"]],
    ["tha", ["Bangkok","Nonthaburi","Samut Prakan","Udon Thani","Chonburi","Chiang Mai","Nakhon Ratchasima","Pak Kret","Hat Yai","Si Racha"]],
    ["phl", ["Quezon City","Manille","Davao","Caloocan","Cebu","Zamboanga","Taguig","Antipolo","Pasig","Cagayán de Oro"]],
    ["jor", ["Amman","Zarqa","Irbid","Russeifa","Al Quwaysimah","Tilā’ al-’Alī","Wadi al-Seer","Al Jubayhah","Khuraybat","Sahab"]],
    ["goa", ["Mormugao","Margao","Mapusa","Panaji","Curchorem","Ponda","Bicholim","Cuncolim","Quepem","Sanquelim"]],
    ["ind", ["Mumbai","Delhi","Bangalore","Hyderabad","Ahmedabad","Chennai","Kolkata","Surat","Pune","Jaipur","Lucknow","Kanpur","Nagpur","Indore","Thane","Bhopal","Visakhapatnam","Pimpri-Chinchwad","Patna","Vadodara"]],
    ["mmr" ["Naypyidaw","Rangoon","Mandalay","Moulmein","Bago","Pathein","Monywa","Meiktila","Sittwe","Mergui"]],
    ["brn", ["Bandar Seri Begawan","Kuala Belait","Seria","Pekan Tutong","Muara","Bangar"]],
    ["sgp", ["Bedok","Jurong West","Tampines","Woodlands","Sengkang","Hougang","Yishun","Choa Chu Kang","Punggol","Ang Mo Kio"]],
    ["mys", ["Kuala Lumpur","Subang Jaya","Kelang","Johor Bahru","Ipoh","Ampang Jaya","Kuching","Petaling Jaya","Shah Alam","Kota Kinabalu"]],
    ["mdv", ["Maafannu","Henveiru","Galolhu","Machchangolhi","Hulhumalé","Vilimalé"]],
    ["idn", ["Jakarta","Surabaya","Medan","Bandung","Bekasi","Tangerang","Makassar","Depok","Semarang","Palembang"]],
    ["khm", ["Phnom Penh","Sihanoukville","Battambang","Siem Reap","Sisophon","Kratie","Kampong Thum","Pouthisat","Ta Khmau","Prey Veng"]],
    ["lka", ["Colombo","Dehiwala-Mount Lavinia","Moratuwa","Sri Jayawardenapura","Negombo","Kandy","Kalmunai","Vavuniya","Galle","Trincomalee"]],
    ["twn", ["Nouveau Taipei","Taichung","Kaohsiung","Taipei","Taoyuan","Tainan","Hsinchu","Keelung","Chiayi","Changhua"]],
    ["prk", ["Pyongyanga","Hamhŭngb","Ch’ŏngjin","Nampho","Wŏnsan","Sinŭiju","Tanch’ŏn","Kaech’ŏn","Kaesŏng","Sariwŏn"]],
    ["kor", ["Séoul","Busan","Incheon","Daegu","Daejeon","Gwangju","Suwon","Ulsan","Changwon","Goyang"]],
    ["kwt", ["Al Ahmadi","Al Asimah","Al Farwaniyah","Al Jahra","Hawalli","Mubarak Al-Kabeer","Koweït"]],
    ["lao", ["Vientiane","Savannakhet","Paksé","Luang Prabang","Phonsavan","Thakhek","Muang Xay","Phiang","Sayaboury","Phonhong"]],
    ["mng", ["Oulan-Bator","Erdenet","Darkhan","Choybalsan","Ölgiy","Saynshand","Ulaangom","Hovd","Mörön","Uliastay"]],
    ["vnm", ["Hô Chi Minh-Ville","Hanoï","Haïphong","Da Nang","Biên Hòa","Hué","Nha Trang","Cần Thơ","Rach Gia","Vũng Tàu"]],
    ["bgd", ["Dhaka","Chittagong","Khulna","Râjshâhî","Sylhet","Tongi","Rangpur","Narayanganj","Maimansingh","Barisal"]],
    ["are", ["Dubaï","Charjah","Abou Dabi","Al Ain","Ajman","Ras el-Khaïmah","Foudjaïrah","Khor Fakkan","Oumm al Qaïwaïn"]],
    ["qat", ["Doha","Al Rayyan","Al Wakrah","Al Khor","Al-Shahaniya","Umm Salal","Al Daayen","Al Shamal"]],
    ["bhr", ["Manama","al-Muharraq","ar-Rifa al-gharbi","Madinat Hamad","A’ali","Madinat ’Isa","Sitra","Al-Budayyia","Jidd Haffs","al-Malikiyya","al-Hidd"]],
    ["omn", ["Sib","Salalah","Matrah","Bawshar","As Sohar","Suwayq","Ibri","Saham","Barka","Rustaq"]],
    ["yem", ["Sanaa","Ta’izz","Al-Hodeïda","Aden","Ibb","Dhamar","Al Moukalla","Zinjibar","Say’un","Ash Shihr"]],
    ["arm", ["Erevan","Gyumri","Vanadzor","Etchmiadzin","Kapan","Abovyan","Hrazdan","Armavir","Goris","Artachat"]],
    ["aze", ["Bakou","Gandja","Sumqayıt","Mingachevir","Qaraçuxur","Şirvan","Nakhitchevan","Bakixanov","Shaki","Ievlakh"]],
    ["cyp", ["Nicosie","Limassol","Stróvolos","Larnaca","Lakatámia","Paphos","Aglantsiá","Káto Polemídia","Éngomi","Mésa Yitoniá"]],
    ["geo", ["Tbilissi","Batoumi","Koutaïssi","Roustavi","Gori","Zougdidi","Poti","Khachouri","Samtredia","Marneouli"]],
    ["kaz", ["Almaty","Noursoultan","Chimkent","Karaganda","Aktioubé","Pavlodar","Taraz","Semeï","Öskemen","Kostanaï"]],
    ["kgz", ["Bichkek","Och","Jalal-Abad","Karakol","Tokmok","Uzgen","Kara-Balta","Balykchy","Naryn","Talas"]],
    ["uzb", ["Tachkent","Samarcande","Namangan","Andijan","Boukhara","Noukous","Karchi","Kokand","Tchirtchik","Ferghana"]],
    ["tjk", ["Douchanbé","Khodjent","Kulob","Qurghonteppa","Istaravchan","Vahdat","Konibodom","Tursunzadė","Isfara","Panjakent"]],
    ["tkm", ["Achgabat","Türkmenabat","Daşoguz","Mary","Balkanabat","Baýramaly","Serdar","Tejen","Türkmenbaşy","Abadan"]],
    ["pse", ["Gaza","Jérusalem-Est","Khan Younès","Hébron","Jabaliya","Rafah","Naplouse","Beit Lahiya","Deir el-Balah","Tulkarem"]],
    ["tls", ["Dili","Baucau","Pante Macassar","Ermera","Lospalos","Maliana","Suai","Viqueque","Bobonaro","Liquiçá"]],
    ["egy", ["Le Caire","Alexandrie","Gizeh","Shubra El-Kheima","Port-Saïd","Suez","Louxor","Mansourah","El-Mahalla el-Koubra","Tanta"]],
    ["lbr", ["Monrovia","Ganta","Buchanan","Gbarnga","Kakata","Voinjama","Zwedru","Harbel","Pleebo","Foya"]],
    ["zaf", ["Le Cap","Durban","Johannesburg","Soweto","Pretoria","Port Elizabeth","Pietermaritzburg","Benoni","Tembisa","Vereeniging"]],
    ["gmb", ["Serrekunda","Brikama","Bakau","Banjul","Farafenni","Lamin","Nema Kunku","Brufut","Basse Santa Su","Gunjur"]],
    ["shn", ["Half Tree Hollow","Jamestown","Georgetown","Édimbourg-des-Sept-Mers"]],
    ["tza", ["Dar es Salaam","Mwanza","Zanzibar","Arusha","Mbeya","Morogoro","Tanga","Dodoma","Kigoma","Moshi"]],
    ["zwe", ["Harare","Bulawayo","Chitungwiza","Mutare","Gweru","Epworth","Kwekwe","Kadoma","Masvingo","Chinhoyi"]],
    ["nam", ["Windhoek","Walvis Bay","Swakopmund","Ondangwa","Lüderitz","Otjiwarongo","Okahandja","Keetmanshoop","Karasburg","Gobabis"]],
    ["cod", ["Kinshasa","Lubumbashi","Mbujimayi","Kananga","Kisangani","Bukavu","Tshikapa","Kolwezi","Likasi","Goma"]],
    ["gnq", ["Bata","Malabo","Ebebiyín","Aconibe","Añisoc","Luba","Evinayong","Mongomo","Mengomeyén","Mikomeseng"]],
    ["eth", ["Addis-Abeba","Dire Dawa","Adama","Gondar","Mekele","Dessie","Baher Dar","Jimma","Debre Zeit","Awasa"]],
    ["lby", ["Tripoli","Benghazi","Misrata","El Beïda","Tarhounah","Khoms","Zaouïa","Zouara","Ajdabiya","Syrte"]],
    ["eri", ["Asmara","Assab","Keren","Massaoua","Édd","Mendefera","Barentu","Adi Keyh","Ghinda","Mersa Fatma"]],
    ["som", ["Mogadiscio","Hargeisa","Boosaaso","Borama","Merka","Kismaayo","Beledweyne","Jamaame","Baidoa","Burao"]],
    ["bdi", ["Bujumbura","Gitega","Ngozi","Rumonge","Kayanza","Muyinga","Makamba","Cibitoke","Rutana","Ruyigi"]],
    ["cmr", ["Douala","Yaoundé","Garoua","Bamenda","Maroua","Nkongsamba","Bafoussam","Ngaoundéré","Bertoua","Loum"]],
    ["caf", ["Bangui","Bimbo","Berbérati","Carnot","Bambari","Bouar","Bria","Bossangoa","Nola","Bangassou"]],
    ["cog", ["Brazzaville","Pointe-Noire","Dolisie","Nkayi","Loandjili","Ouesso","Madingou","Owando","Gamboma","Impfondo"]],
    ["civ", ["Abidjan","Bouaké","Daloa","Yamoussoukro","San-Pédro","Divo","Korhogo","Anyama","Abengourou","Man"]],
    ["ben", ["Cotonou","Abomey-Calavi","Porto-Novo","Parakou","Djougou","Bohicon","Natitingou","Savé","Abomey","Nikki"]],
    ["gab", ["Libreville","Port-Gentil","Franceville","Oyem","Moanda","Mouila","Lambaréné","Tchibanga","Koulamoutou","Makokou"]],
    ["gha", ["Accra","Kumasi","Tamale","Sekondi-Takoradi","Ashaiman","Sunyani","Cape Coast","Obuasi","Teshie","Tema"]],
    ["gin", ["Conakry","N’Zérékoré","Kankan","Kindia","Siguiri","Boké","Kissidougou","Labé","Dubréka","Kamsar"]],
    ["bfa", ["Ouagadougou","Bobo-Dioulasso","Koudougou","Banfora","Ouahigouya","Dédougou","Pissila","Kaya","Tanghin-Dassouri","Tenkodogo"]],
    ["ken", ["Nairobi","Mombasa","Kisumu","Nakuru","Eldoret","Ruiru","Machakos","Meru","Nyeri","Kitale"]],
    ["mdg", ["Tananarive","Tamatave","Antsirabé","Fianarantsoa","Majunga","Tuléar","Diego-Suarez","Antanifotsy","Ambovombe","Amparafaravola"]],
    ["mwi", ["Lilongwe","Blantyre","Mzuzu","Zomba","Kasungu","Mangochi","Karonga","Salima","Nkhotakota","Liwonde"]],
    ["mli", ["Bamako","Sikasso","Mopti","Koutiala","Kayes","Ségou","Nioro du Sahel","Niono","Markala","Kolondiéba"]],
    ["mrt", ["Nouakchott","Nouâdhibou","Rosso","Adel Bagrou","Boghé","Kiffa","Zouerate","Kaédi","Boû Gâdoûm","Boutilimit"]],
    ["ner", ["Niamey","Zinder","Maradi","Tessaoua","Birni N’Konni","Aguié","Tanout","Illéla","Agadez","Tahoua"]],
    ["nga", ["Lagos","Kano","Ibadan","Kaduna","Port Harcourt","Maiduguri","Benin City","Zaria","Aba","Ogbomosho	"]],
    ["uga", ["Kampala","Gulu","Lira","Jinja","Mukono","Mbarara","Kasese","Mbale","Kitgum","Njeru"]],
    ["rwa", ["Kigali","Butare","Gitarama","Ruhengeri","Gisenyi","Byumba","Cyangugu","Nyanza","Kabuga","Ruhango"]],
    ["sen", ["Dakar","Pikine","Touba","Guédiawaye","Thiès","Kaolack","Mbour","Saint-Louis","Rufisque","Ziguinchor"]],
    ["sle", ["Freetown","Bo","Kenema","Makeni","Koidu","Lunsar","Port Loko","Pandebu","Kabala","Waterloo"]],
    ["sdn", ["Omdourman","Khartoum","Bahri","Nyala","Port-Soudan","Kassala","al-Ubayyid","Kosti","Wad Madani","al-Qadarif"]],
    ["tcd", ["N’Djaména","Moundou","Abeche","Sarh","Faya-Largeau","Koumra","Kelo","Mongo","Pala","Am Timan"]],
    ["tgo", ["Lomé","Sokodé","Kara","Kpalimé","Atakpamé","Bassar","Tsévié","Aného","Mango","Dapaong"]],
    ["zmb", ["Lusaka","Ndola","Kitwe","Kabwe","Chingola","Mufulira","Livingstone","Luanshya","Kasama","Chipata"]],
    ["bwa", ["Gaborone","Francistown","Molepolole","Selebi-Phikwe","Maun","Serowe","Mogoditshane","Kanye","Mahalapye","Mochudi"]],
    ["lso", ["Maseru","Teyateyaneng","Mafeteng","Hlotse","Mohale’s Hoek","Maputsoe","Qacha’s Nek","Quthing","Peka","Butha-Buthe"]],
    ["ssd", ["Djouba","Wau","Malakal","Yei","Yambio","Kuajok","Renk","Bor","Aweil","Maridi"]],
    ["mar", ["Casablanca","Fès","Tanger","Marrakech","Salé","Meknès","Rabat","Oujda","Kénitra","Agadir"]],
    ["tun", ["Tunis","Sfax","Sousse","Kairouan","Bizerte","Gabès","La Soukra","Ariana","Sidi Hassine","El Mourouj"]],
    ["dza", ["Alger","Oran","Constantine","Annaba","Blida","Batna","Djelfa","Sétif","Sidi bel Abbès","Biskra"]],
    ["mus", ["Port Louis","Beau-Bassin Rose-Hill","Vacoas-Phœnix","Curepipe","Quatre Bornes","Trou-aux-Biches","Goodlands","Centre de Flacq","Bel Air","Mahébourg"]],
    ["swz", ["Manzini","Mbabane","Big Bend","Malkerns","Nhlangano","Mhlume","Hluti","Simunye","Siteki","Pigg’s Peak"]],
    ["gnb", ["Bissau","Bafatá","Gabu","Bissorã","Bolama","Cacheu","Bubaque","Catió","Mansôa","Buba"]],
    ["moz", ["Maputo","Matola","Beira","Nampula","Chimoio","Nacala","Quelimane","Mocuba","Tete","Xai-Xai"]],
    ["stp", ["São Tomé","Santo Amaro","Neves","Santana","Trindade","Santa Cruz","Pantufo","Guadalupe","Santo António","Santa Catarina"]],
    ["ago", ["Luanda","Huambo","Lobito","Benguela","Lucapa","Kuito","Lubango","Malanje","Namibe","Soyo"]],
    ["cpv", ["Praia","Mindelo","Santa Maria","Assomada","Porto Novo","Pedra Badejo","São Filipe","Tarrafal","Espargos","Calheta de São Miguel"]],
    ["com", ["Moroni","Mutsamudu","Domoni","Fomboni","Tsembéhou"]],
    ["syc", ["Victoria","De Quincey","Anse Boileau","Anse Volbert","Beau Vallon","Anse Royale","Bel Ombre","Cascade","Machabee","Grand Anse"]],
    ["dji", ["Djibouti","Ali Sabieh","Tadjourah","Obock","Dikhil","Arta","Holhol","Dorra","Galafi","Loyada"]],
    ["can", ["Toronto","Montréal","Calgary","Ottawa","Edmonton","Mississauga","Winnipeg","Vancouver","Brampton","Hamilton"]],
    ["usa", ["New York","Los Angeles","Chicago","Houston","Washington, D.C.","San Francisco","Philadelphie","Dallas","Détroit","Miami"]],
    ["mex", ["Mexico","Ecatepec","Guadalajara","Puebla","Juárez","Tijuana","León","Nezahualcóyotl","Monterrey","Zapopan"]],
    ["cri", ["San José","Puerto Limón","San Francisco","Alajuela","Liberia","Paraíso","Desamparados","San Isidro de El General","Puntarenas","Curridabat"]],
    ["cub", ["La Havane","Santiago de Cuba","Camagüey","Holguín","Guantánamo","Santa Clara","Las Tunas","Bayamo","Cienfuegos","Pinar del Río"]],
    ["dom", ["Saint-Domingue","Santiago de los Caballeros","San Pedro de Macorís","La Romana","Los Alcarrizos","San Cristóbal","Higüey","San Francisco de Macorís","Puerto Plata","Concepción de la Vega"]],
    ["gtm", ["Guatemala","Mixco","Villa Nueva","Quetzaltenango","San Miguel Petapa","Escuintla","San Juan Sacatepéquez","Villa Canales","Chinautla","Chimaltenango"]],
    ["hti", ["Port-au-Prince","Carrefour","Delmas","Cap-Haïtien","Pétionville","Les Gonaïves","Saint-Marc","Les Cayes","Verrettes","Port-de-Paix"]],
    ["hnd", ["Tegucigalpa","San Pedro Sula","Choloma","La Ceiba","El Progreso","Choluteca","Comayagua","Puerto Cortés","La Lima","Danlí"]],
    ["nic", ["Managua","León","Chinandega","Masaya","Estelí","Tipitapa","Matagalpa","Granada","Ciudad Sandino","Juigalpa"]],
    ["pan", ["Panama","San Miguelito","Tocumen","David","Las Cumbres","Colón","La Chorrera","Pacora","Santiago de Veraguas","Chitré"]],
    ["slv", ["San Salvador","Soyapango","Santa Ana","San Miguel","Mejicanos","Apopa","Delgado","Santa Tecla","Ilopango","Colón"]],
    ["arg", ["Buenos Aires","Córdoba","Rosario","Mendoza","San Miguel de Tucumán","La Plata","Mar del Plata","Salta","Santa Fe","San Juan"]],
    ["bra", ["São Paulo","Rio de Janeiro","Salvador da Bahia","Brasília","Fortaleza","Belo Horizonte","Curitiba","Manaus","Recife","Porto Alegre"]],
    ["chl", ["Santiago du Chili","Puente Alto","Viña del Mar","Antofagasta","Valparaíso","San Bernardo","Temuco","Rancagua","Concepción","Arica"]],
    ["bol", ["Santa Cruz de la Sierra","El Alto","La Paz","Cochabamba","Oruro","Sucre","Tarija","Potosí","Sacaba","Quillacollo"]],
    ["col", ["Bogota","Medellín","Cali","Barranquilla","Cúcuta","Carthagène des Indes","Bucaramanga","Soledad","Pereira","Ibagué"]],
    ["ecu", ["Guayaquil","Quito	","Cuenca","Santo Domingo","Machala","Durán","Portoviejo","Manta","Loja","Ambato"]],
    ["pry", ["Asuncion","Ciudad del Este","San Lorenzo","Luque","Capiatá","Lambaré","Fernando de la Mora","Limpio","Ñemby","Encarnación"]],
    ["per", ["Lima","Arequipa","Trujillo","Chiclayo","Piura","Iquitos","Cusco","Huancayo","Chimbote","Pucallpa"]],
    ["ury", ["Montevideo","Ciudad de la Costa","Salto","Paysandú","Las Piedras","Rivera","Maldonado","Tacuarembó","Melo","Mercedes"]],
    ["ven", ["Maracaibo","Caracas","Valencia","Barquisimeto","Ciudad Guayana","Barcelona","Maturín","Maracay","Petare","Turmero"]],
    ["aia", ["North Side","South Hill","Stoney Ground","The Valley","Island Harbour","The Quarter","George Hill","Blowing Point","West End","East End"]],
    ["bmu", ["Hamilton","St. George’s"]],
    ["cym", ["George Town","West Bay","Bodden Town","North Side","East End","Cayman Brac","Little Cayman"]],
    ["msr", ["Salem","Brades","Davy Hill","Little Bay","Woodlands","Cork Hill","Old Towne "]],
    ["tca", ["Cockburn Town","Downtown Providenciales","Cockburn Harbour","Bottle Creek","Wheeland","Leeward","Long Bay","Chalk Sound","Blue Hills","The Bight","Five Cays"]],
    ["jam", ["Kingston","Spanish Town","Portmore","Montego Bay","Mandeville","May Pen","Old Harbour","Linstead","Savanna-la-Mar","Half Way Tree"]],
    ["guy", ["Georgetown","Linden","Nouvelle-Amsterdam","Corriverton","Rose Hall","Skeldon","Rosignol","Mahaica","Ituni","Paradise"]],
    ["blz", ["Belize City","San Ignacio","Belmopan","San Pedro","Orange Walk Town","Corozal Town","Dangriga","Benque Viejo","Ladyville","Punta Gorda"]],
    ["pri", ["San Juan","Bayamón","Ponce","Carolina","Caguas","Guaynabo","Arecibo","Toa Baja","Mayagüez","Trujillo Alto"]],
    ["tto", ["Chaguanas","San Fernando","Port d’Espagne","Arima","Marabella","Point Fortin","Morvant","Tacarigua","Tunapuna","San Juan"]],
    ["brb", ["Bridgetown","Speightstown","Holetown","Bathsheba","Oistins","Bulkeley","Crane","Grab Hill","Blackmans","Greenland"]],
    ["grd", ["Saint-Georges","Gouyave","Grenville","Victoria","Saint David","Sauteurs","Hillsborough"]],
    ["bhs", ["Nassau","Freeport","West End","Coopers Town","Marsh Harbour","High Rock","George Town","Andros Town","Clarence Town","Arthur’s Town"]],
    ["sur", ["Paramaribo","Lelydorp","Nieuw Nickerie","Moengo","Meerzorg","Nieuw-Amsterdam","Marienburg","Wageningen","Albina","Groningen"]],
    ["dma", ["Roseau","Portsmouth","Marigot","Berekua","Atkinson","Mahaut","Canefield","Saint-Joseph","Wesley","Salisbury"]],
    ["lca", ["Anse-la-Raye","Canaries","Castries","Choiseul","Dennery","Gros Islet","Laborie","Micoud","Soufrière","Vieux-Fort"]],
    ["vct", ["Kingstown","Port Elizabeth"]],
    ["atg", ["Saint John’s","All Saints","Liberta","Potters village","Bolands","Swetes","Cedar Grove","Parham","Carlisle","Pigotts"]],
    ["kna", ["Basseterre","Cayon","Charlestown","Dieppe Bay Town","Gingerland","Newcastle","Old Road Town","Sandy Point Town"]],
    ["cuw", ["Willemstad"]],
    ["aus", ["Sydney","Melbourne","Brisbane","Perth","Adelaide","Gold Coast","Canberra","Newcastle","Wollongong","Geelong"]],
    ["niu", ["Alofi"]],
    ["nzl", ["Auckland","Christchurch","Wellington","Hamilton","Tauranga","Lower Hutt","Dunedin","Palmerston North","Napier","Hibiscus Coast"]],
    ["tkl", ["Atafu","Nukunonu","Fakaofo"]],
    ["wsm", ["Apia","Salelologa","Vaitele","Faleasi’u"]],
    ["nru", ["Aiwo","Anabar","Anetan","Anibare","Baiti","Boe","Buada","Denigomodu","Ewa","Ijuw","Meneng","Nibok","Uaboe","Yaren"]],
    ["fji", ["Nasinu","Suva","Lautoka","Nausori","Nadi","Labasa","Lami","Ba","Sigatoka","Savusavu"]],
    ["ton", ["Mu’a","Neiafu","Nuku’alofa","Pangai"]],
    ["png", ["Port Moresby","Lae","Mendi","Popondetta","Mount Hagen","Kokopo","Arawa","Madang","Kimbe","Bulolo"]],
    ["tuv", ["Asau","Lolua","Tanrake","Vaiaku"]],
    ["slb", ["Honiara","Auki","Gizo","Munda","Noro","Buala","Kirakira","Tulagi","Lata"]],
    ["kir", ["Tarawa-Sud", "Banaba","Tarawa","North Gilbert Islands","Central Gilbert Islands","South Gilbert Islands","Phoenix Islands","Line Islands"]],
    ["vut", ["Port Vila","Luganville"]],
    ["mhl", ["Delap-Uliga-Darrit","Ebeye","Rairok","Laura"]],
    ["fsm", ["Palikir","Weno","Tofol","Kolonia","Colonia"]],
    ["plw", ["Koror","Meyuns","Airai","Kloulklubed","Melekeok"]],
];


const _defaut = 'fra'
const _paysVilles = new Map(iso3Villes);
const _listeVilles = envoi => _paysVilles.has(envoi) ? _paysVilles.get(envoi) : _paysVilles.get(_defaut);

const planete = [
    {region:"europe", insee:"00000", iso2:"fr", iso3:"fra", nom:"France", villes: _listeVilles("fra")},
    {region:"europe", insee:"99101", iso2:"dk", iso3:"dnk", nom:"Danemark", villes: _listeVilles("dnk")},
    {region:"europe", insee:"99102", iso2:"is", iso3:"isl", nom:"Islande", villes: _listeVilles("isl")},
    {region:"europe", insee:"99103", iso2:"no", iso3:"nor", nom:"Norvège", villes: _listeVilles("nor")},
    {region:"europe", insee:"99104", iso2:"se", iso3:"swe", nom:"Suède", villes: _listeVilles("swe")},
    {region:"europe", insee:"99105", iso2:"fi", iso3:"fin", nom:"Finlande", villes: _listeVilles("fin")},
    {region:"europe", insee:"99106", iso2:"ee", iso3:"est", nom:"Estonie", villes: _listeVilles("est")},
    {region:"europe", insee:"99107", iso2:"lv", iso3:"lva", nom:"Lettonie", villes: _listeVilles("lva")},
    {region:"europe", insee:"99108", iso2:"lt", iso3:"ltu", nom:"Lituanie", villes: _listeVilles("ltu")},
    {region:"europe", insee:"99109", iso2:"de", iso3:"deu", nom:"Allemagne", villes: _listeVilles("deu")},
    {region:"europe", insee:"99110", iso2:"at", iso3:"aut", nom:"Autriche", villes: _listeVilles("aut")},
    {region:"europe", insee:"99111", iso2:"bg", iso3:"bgr", nom:"Bulgarie", villes: _listeVilles("bgr")},
    {region:"europe", insee:"99112", iso2:"hu", iso3:"hun", nom:"Hongrie", villes: _listeVilles("hun")},
    {region:"europe", insee:"99113", iso2:"li", iso3:"lie", nom:"Liechtenstein", villes: _listeVilles("lie")},
    {region:"europe", insee:"99114", iso2:"ro", iso3:"rou", nom:"Roumanie", villes: _listeVilles("rou")},
    {region:"europe", insee:"99116", iso2:"cz", iso3:"cze", nom:"Tchéquie", villes: _listeVilles("cze")},
    {region:"europe", insee:"99117", iso2:"sk", iso3:"svk", nom:"Slovaquie", villes: _listeVilles("svk")},
    {region:"europe", insee:"99118", iso2:"ba", iso3:"bih", nom:"Bosnie-Herzégovine", villes: _listeVilles("bih")},
    {region:"europe", insee:"99119", iso2:"hr", iso3:"hrv", nom:"Croatie", villes: _listeVilles("hrv")},
    {region:"europe", insee:"99120", iso2:"me", iso3:"mne", nom:"Montenegro", villes: _listeVilles("mne")},
    {region:"europe", insee:"99121", iso2:"rs", iso3:"srb", nom:"Serbie", villes: _listeVilles("srb")},
    {region:"europe", insee:"99122", iso2:"pl", iso3:"pol", nom:"Pologne", villes: _listeVilles("pol")},
    {region:"europe", insee:"99123", iso2:"ru", iso3:"rus", nom:"Russie", villes: _listeVilles("rus")},
    {region:"europe", insee:"99125", iso2:"al", iso3:"alb", nom:"Albanie", villes: _listeVilles("alb")},
    {region:"europe", insee:"99126", iso2:"gr", iso3:"grc", nom:"Grèce", villes: _listeVilles("grc")},
    {region:"europe", insee:"99127", iso2:"it", iso3:"ita", nom:"Italie", villes: _listeVilles("ita")},
    {region:"europe", insee:"99128", iso2:"sm", iso3:"smr", nom:"Saint-Marin", villes: _listeVilles("smr")},
    {region:"europe", insee:"99129", iso2:"va", iso3:"vat", nom:"Vatican", villes: _listeVilles("vat")},
    {region:"europe", insee:"99130", iso2:"ad", iso3:"and", nom:"Andorre", villes: _listeVilles("and")},
    {region:"europe", insee:"99131", iso2:"be", iso3:"bel", nom:"Belgique", villes: _listeVilles("bel")},
    {region:"europe", insee:"99132", iso2:"gb", iso3:"gbr", nom:"Royaume-Uni", villes: _listeVilles("gbr")},
    {region:"europe", insee:"99134", iso2:"es", iso3:"esp", nom:"Espagne", villes: _listeVilles("esp")},
    {region:"europe", insee:"99135", iso2:"nl", iso3:"nld", nom:"Pays-Bas", villes: _listeVilles("nld")},
    {region:"europe", insee:"99136", iso2:"ie", iso3:"irl", nom:"Irlande", villes: _listeVilles("irl")},
    {region:"europe", insee:"99137", iso2:"lu", iso3:"lux", nom:"Luxembourg", villes: _listeVilles("lux")},
    {region:"europe", insee:"99138", iso2:"mc", iso3:"mco", nom:"Monaco", villes: _listeVilles("mco")},
    {region:"europe", insee:"99139", iso2:"pt", iso3:"prt", nom:"Portugal", villes: _listeVilles("prt")},
    {region:"europe", insee:"99140", iso2:"ch", iso3:"che", nom:"Suisse", villes: _listeVilles("che")},
    {region:"europe", insee:"99144", iso2:"mt", iso3:"mlt", nom:"Malte", villes: _listeVilles("mlt")},
    {region:"europe", insee:"99145", iso2:"si", iso3:"svn", nom:"Slovénie", villes: _listeVilles("svn")},
    {region:"europe", insee:"99148", iso2:"by", iso3:"blr", nom:"Biélorussie", villes: _listeVilles("blr")},
    {region:"europe", insee:"99151", iso2:"md", iso3:"mda", nom:"Moldavie", villes: _listeVilles("mda")},
    {region:"europe", insee:"99155", iso2:"ua", iso3:"ukr", nom:"Ukraine", villes: _listeVilles("ukr")},
    {region:"europe", insee:"99156", iso2:"mk", iso3:"mkd", nom:"Macédoine du Nord", villes: _listeVilles("mkd")},
    {region:"europe", insee:"99157", iso2:"xk", iso3:"xxk", nom:"Kosovo", villes: _listeVilles("xxk")},
    {region:"asie", insee:"99201", iso2:"sa", iso3:"sau", nom:"Arabie Saoudite", villes: _listeVilles("sau")},
    {region:"asie", insee:"99202", iso2:"ye", iso3:"yem", nom:"Yémen", villes: _listeVilles("yem")},
    {region:"asie", insee:"99203", iso2:"iq", iso3:"irq", nom:"Iraq", villes: _listeVilles("irq")},
    {region:"asie", insee:"99204", iso2:"ir", iso3:"irn", nom:"Iran", villes: _listeVilles("irn")},
    {region:"asie", insee:"99205", iso2:"lb", iso3:"lbn", nom:"Liban", villes: _listeVilles("lbn")},
    {region:"asie", insee:"99206", iso2:"sy", iso3:"syr", nom:"Syrie", villes: _listeVilles("syr")},
    {region:"asie", insee:"99207", iso2:"il", iso3:"isr", nom:"Israël", villes: _listeVilles("isr")},
    {region:"asie", insee:"99208", iso2:"tr", iso3:"tur", nom:"Turquie", villes: _listeVilles("tur")},
    {region:"asie", insee:"99212", iso2:"af", iso3:"afg", nom:"Afghanistan", villes: _listeVilles("afg")},
    {region:"asie", insee:"99213", iso2:"pk", iso3:"pak", nom:"Pakistan", villes: _listeVilles("pak")},
    {region:"asie", insee:"99214", iso2:"bt", iso3:"btn", nom:"Bhoutan", villes: _listeVilles("btn")},
    {region:"asie", insee:"99215", iso2:"np", iso3:"npl", nom:"Népal", villes: _listeVilles("npl")},
    {region:"asie", insee:"99216", iso2:"cn", iso3:"chn", nom:"Chine", villes: _listeVilles("chn")},
    {region:"asie", insee:"99217", iso2:"jp", iso3:"jpn", nom:"Japon", villes: _listeVilles("jpn")},
    {region:"asie", insee:"99219", iso2:"th", iso3:"tha", nom:"Thaïlande", villes: _listeVilles("tha")},
    {region:"asie", insee:"99220", iso2:"ph", iso3:"phl", nom:"Philippines", villes: _listeVilles("phl")},
    {region:"asie", insee:"99222", iso2:"jo", iso3:"jor", nom:"Jordanie", villes: _listeVilles("jor")},
    {region:"asie", insee:"99223", iso2:"in", iso3:"ind", nom:"Inde", villes: _listeVilles("ind")},
    {region:"asie", insee:"99224", iso2:"mm", iso3:"mmr", nom:"Birmanie", villes: _listeVilles("mmr")},
    {region:"asie", insee:"99225", iso2:"bn", iso3:"brn", nom:"Brunei", villes: _listeVilles("brn")},
    {region:"asie", insee:"99226", iso2:"sg", iso3:"sgp", nom:"Singapour", villes: _listeVilles("sgp")},
    {region:"asie", insee:"99227", iso2:"my", iso3:"mys", nom:"Malaisie", villes: _listeVilles("mys")},
    {region:"asie", insee:"99229", iso2:"mv", iso3:"mdv", nom:"Maldives", villes: _listeVilles("mdv")},
    {region:"asie", insee:"99230", iso2:"hk", iso3:"hkg", nom:"Hong-Kong", villes: _listeVilles("hkg")},
    {region:"asie", insee:"99231", iso2:"id", iso3:"idn", nom:"Indonésie", villes: _listeVilles("idn")},
    {region:"asie", insee:"99234", iso2:"kh", iso3:"khm", nom:"Cambodge", villes: _listeVilles("khm")},
    {region:"asie", insee:"99235", iso2:"lk", iso3:"lka", nom:"Sri Lanka", villes: _listeVilles("lka")},
    {region:"asie", insee:"99236", iso2:"tw", iso3:"twn", nom:"Taïwan", villes: _listeVilles("twn")},
    {region:"asie", insee:"99238", iso2:"kp", iso3:"prk", nom:"Corée du Nord", villes: _listeVilles("prk")},
    {region:"asie", insee:"99239", iso2:"kr", iso3:"kor", nom:"Corée du Sud", villes: _listeVilles("kor")},
    {region:"asie", insee:"99240", iso2:"kw", iso3:"kwt", nom:"Koweit", villes: _listeVilles("kwt")},
    {region:"asie", insee:"99241", iso2:"la", iso3:"lao", nom:"Laos", villes: _listeVilles("lao")},
    {region:"asie", insee:"99242", iso2:"mn", iso3:"mng", nom:"Mongolie", villes: _listeVilles("mng")},
    {region:"asie", insee:"99243", iso2:"vn", iso3:"vnm", nom:"Viêt Nam", villes: _listeVilles("vnm")},
    {region:"asie", insee:"99246", iso2:"bd", iso3:"bgd", nom:"Bangladesh", villes: _listeVilles("bgd")},
    {region:"asie", insee:"99247", iso2:"ae", iso3:"are", nom:"Émirats Arabes Unis", villes: _listeVilles("are")},
    {region:"asie", insee:"99248", iso2:"qa", iso3:"qat", nom:"Qatar", villes: _listeVilles("qat")},
    {region:"asie", insee:"99249", iso2:"bh", iso3:"bhr", nom:"Bahrein", villes: _listeVilles("bhr")},
    {region:"asie", insee:"99250", iso2:"om", iso3:"omn", nom:"Oman", villes: _listeVilles("omn")},
    {region:"asie", insee:"99251", iso2:"ye", iso3:"yem", nom:"Yémen", villes: _listeVilles("yem")},
    {region:"asie", insee:"99252", iso2:"am", iso3:"arm", nom:"Arménie", villes: _listeVilles("arm")},
    {region:"asie", insee:"99253", iso2:"az", iso3:"aze", nom:"Azerbaidjan", villes: _listeVilles("aze")},
    {region:"asie", insee:"99254", iso2:"cy", iso3:"cyp", nom:"Chypre", villes: _listeVilles("cyp")},
    {region:"asie", insee:"99255", iso2:"ge", iso3:"geo", nom:"Géorgie", villes: _listeVilles("geo")},
    {region:"asie", insee:"99256", iso2:"kz", iso3:"kaz", nom:"Kazakhstan", villes: _listeVilles("kaz")},
    {region:"asie", insee:"99257", iso2:"kg", iso3:"kgz", nom:"Kirghizistan", villes: _listeVilles("kgz")},
    {region:"asie", insee:"99258", iso2:"uz", iso3:"uzb", nom:"Ouzbekistan", villes: _listeVilles("uzb")},
    {region:"asie", insee:"99259", iso2:"tj", iso3:"tjk", nom:"Tadjikistan", villes: _listeVilles("tjk")},
    {region:"asie", insee:"99260", iso2:"tm", iso3:"tkm", nom:"Turkménistan", villes: _listeVilles("tkm")},
    {region:"asie", insee:"99261", iso2:"ps", iso3:"pse", nom:"Palestine", villes: _listeVilles("pse")},
    {region:"asie", insee:"99262", iso2:"tl", iso3:"tls", nom:"Timor Oriental", villes: _listeVilles("tls")},
    {region:"afrique", insee:"99301", iso2:"eg", iso3:"egy", nom:"Égypte", villes: _listeVilles("egy")},
    {region:"afrique", insee:"99302", iso2:"lr", iso3:"lbr", nom:"Liberia", villes: _listeVilles("lbr")},
    {region:"afrique", insee:"99303", iso2:"za", iso3:"zaf", nom:"Afrique du Sud", villes: _listeVilles("zaf")},
    {region:"afrique", insee:"99304", iso2:"gm", iso3:"gmb", nom:"Gambie", villes: _listeVilles("gmb")},
    {region:"afrique", insee:"99309", iso2:"tz", iso3:"tza", nom:"Tanzanie", villes: _listeVilles("tza")},
    {region:"afrique", insee:"99310", iso2:"zw", iso3:"zwe", nom:"Zimbabwe", villes: _listeVilles("zwe")},
    {region:"afrique", insee:"99311", iso2:"na", iso3:"nam", nom:"Namibie", villes: _listeVilles("nam")},
    {region:"afrique", insee:"99312", iso2:"cd", iso3:"cod", nom:"Congo (République Démocratique)", villes: _listeVilles("cod")},
    {region:"afrique", insee:"99314", iso2:"gq", iso3:"gnq", nom:"Guinée Équatoriale", villes: _listeVilles("gnq")},
    {region:"afrique", insee:"99315", iso2:"et", iso3:"eth", nom:"Éthiopie", villes: _listeVilles("eth")},
    {region:"afrique", insee:"99316", iso2:"ly", iso3:"lby", nom:"Libye", villes: _listeVilles("lby")},
    {region:"afrique", insee:"99317", iso2:"er", iso3:"eri", nom:"Érythrée", villes: _listeVilles("eri")},
    {region:"afrique", insee:"99318", iso2:"so", iso3:"som", nom:"Somalie", villes: _listeVilles("som")},
    {region:"afrique", insee:"99321", iso2:"bi", iso3:"bdi", nom:"Burundi", villes: _listeVilles("bdi")},
    {region:"afrique", insee:"99322", iso2:"cm", iso3:"cmr", nom:"Cameroun", villes: _listeVilles("cmr")},
    {region:"afrique", insee:"99323", iso2:"cf", iso3:"caf", nom:"Centrafricaine (République)", villes: _listeVilles("caf")},
    {region:"afrique", insee:"99324", iso2:"cg", iso3:"cog", nom:"Congo", villes: _listeVilles("cog")},
    {region:"afrique", insee:"99326", iso2:"ci", iso3:"civ", nom:"Côte d’Ivoire", villes: _listeVilles("civ")},
    {region:"afrique", insee:"99327", iso2:"bj", iso3:"ben", nom:"Bénin", villes: _listeVilles("ben")},
    {region:"afrique", insee:"99328", iso2:"ga", iso3:"gab", nom:"Gabon", villes: _listeVilles("gab")},
    {region:"afrique", insee:"99329", iso2:"gh", iso3:"gha", nom:"Ghana", villes: _listeVilles("gha")},
    {region:"afrique", insee:"99330", iso2:"gn", iso3:"gin", nom:"Guinée", villes: _listeVilles("gin")},
    {region:"afrique", insee:"99331", iso2:"bf", iso3:"bfa", nom:"Burkina", villes: _listeVilles("bfa")},
    {region:"afrique", insee:"99332", iso2:"ke", iso3:"ken", nom:"Kenya", villes: _listeVilles("ken")},
    {region:"afrique", insee:"99333", iso2:"mg", iso3:"mdg", nom:"Madagascar", villes: _listeVilles("mdg")},
    {region:"afrique", insee:"99334", iso2:"mw", iso3:"mwi", nom:"Malawi", villes: _listeVilles("mwi")},
    {region:"afrique", insee:"99335", iso2:"ml", iso3:"mli", nom:"Mali", villes: _listeVilles("mli")},
    {region:"afrique", insee:"99336", iso2:"mr", iso3:"mrt", nom:"Mauritanie", villes: _listeVilles("mrt")},
    {region:"afrique", insee:"99337", iso2:"ne", iso3:"ner", nom:"Niger", villes: _listeVilles("ner")},
    {region:"afrique", insee:"99338", iso2:"ng", iso3:"nga", nom:"Nigéria", villes: _listeVilles("nga")},
    {region:"afrique", insee:"99339", iso2:"ug", iso3:"uga", nom:"Ouganda", villes: _listeVilles("uga")},
    {region:"afrique", insee:"99340", iso2:"rw", iso3:"rwa", nom:"Rwanda", villes: _listeVilles("rwa")},
    {region:"afrique", insee:"99341", iso2:"sn", iso3:"sen", nom:"Sénégal", villes: _listeVilles("sen")},
    {region:"afrique", insee:"99342", iso2:"sl", iso3:"sle", nom:"Sierra Leone", villes: _listeVilles("sle")},
    {region:"afrique", insee:"99343", iso2:"sd", iso3:"sdn", nom:"Soudan", villes: _listeVilles("sdn")},
    {region:"afrique", insee:"99344", iso2:"td", iso3:"tcd", nom:"Tchad", villes: _listeVilles("tcd")},
    {region:"afrique", insee:"99345", iso2:"tg", iso3:"tgo", nom:"Togo", villes: _listeVilles("tgo")},
    {region:"afrique", insee:"99346", iso2:"zm", iso3:"zmb", nom:"Zambie", villes: _listeVilles("zmb")},
    {region:"afrique", insee:"99347", iso2:"bw", iso3:"bwa", nom:"Botswana", villes: _listeVilles("bwa")},
    {region:"afrique", insee:"99348", iso2:"ls", iso3:"lso", nom:"Lesotho", villes: _listeVilles("lso")},
    {region:"afrique", insee:"99349", iso2:"ss", iso3:"ssd", nom:"Soudan du Sud", villes: _listeVilles("ssd")},
    {region:"afrique", insee:"99350", iso2:"ma", iso3:"mar", nom:"Maroc", villes: _listeVilles("mar")},
    {region:"afrique", insee:"99351", iso2:"tn", iso3:"tun", nom:"Tunisie", villes: _listeVilles("tun")},
    {region:"afrique", insee:"99352", iso2:"dz", iso3:"dza", nom:"Algérie", villes: _listeVilles("dza")},
    {region:"afrique", insee:"99389", iso2:"eh", iso3:"esh", nom:"Sahara Occidental", villes: _listeVilles("esh")},
    {region:"afrique", insee:"99390", iso2:"mu", iso3:"mus", nom:"Maurice", villes: _listeVilles("mus")},
    {region:"afrique", insee:"99391", iso2:"sz", iso3:"swz", nom:"Eswatini", villes: _listeVilles("swz")},
    {region:"afrique", insee:"99392", iso2:"gw", iso3:"gnb", nom:"Guinée-Bissau", villes: _listeVilles("gnb")},
    {region:"afrique", insee:"99393", iso2:"mz", iso3:"moz", nom:"Mozambique", villes: _listeVilles("moz")},
    {region:"afrique", insee:"99394", iso2:"st", iso3:"stp", nom:"São Tomé-et-Principe", villes: _listeVilles("stp")},
    {region:"afrique", insee:"99395", iso2:"ao", iso3:"ago", nom:"Angola", villes: _listeVilles("ago")},
    {region:"afrique", insee:"99396", iso2:"cv", iso3:"cpv", nom:"Cap-Vert", villes: _listeVilles("cpv")},
    {region:"afrique", insee:"99397", iso2:"km", iso3:"com", nom:"Comores", villes: _listeVilles("com")},
    {region:"afrique", insee:"99398", iso2:"sc", iso3:"syc", nom:"Seychelles", villes: _listeVilles("syc")},
    {region:"afrique", insee:"99399", iso2:"dj", iso3:"dji", nom:"Djibouti", villes: _listeVilles("dji")},
    {region:"amerique", insee:"99401", iso2:"ca", iso3:"can", nom:"Canada", villes: _listeVilles("can")},
    {region:"amerique", insee:"99404", iso2:"us", iso3:"usa", nom:"États-Unis", villes: _listeVilles("usa")},
    {region:"amerique", insee:"99405", iso2:"mx", iso3:"mex", nom:"Mexique", villes: _listeVilles("mex")},
    {region:"amerique", insee:"99406", iso2:"cr", iso3:"cri", nom:"Costa Rica", villes: _listeVilles("cri")},
    {region:"amerique", insee:"99407", iso2:"cu", iso3:"cub", nom:"Cuba", villes: _listeVilles("cub")},
    {region:"amerique", insee:"99408", iso2:"do", iso3:"dom", nom:"Dominicaine (République)", villes: _listeVilles("dom")},
    {region:"amerique", insee:"99409", iso2:"gt", iso3:"gtm", nom:"Guatemala", villes: _listeVilles("gtm")},
    {region:"amerique", insee:"99410", iso2:"ht", iso3:"hti", nom:"Haïti", villes: _listeVilles("hti")},
    {region:"amerique", insee:"99411", iso2:"hn", iso3:"hnd", nom:"Honduras", villes: _listeVilles("hnd")},
    {region:"amerique", insee:"99412", iso2:"ni", iso3:"nic", nom:"Nicaragua", villes: _listeVilles("nic")},
    {region:"amerique", insee:"99413", iso2:"pa", iso3:"pan", nom:"Panama", villes: _listeVilles("pan")},
    {region:"amerique", insee:"99414", iso2:"sv", iso3:"slv", nom:"El Salvador", villes: _listeVilles("slv")},
    {region:"amerique", insee:"99415", iso2:"ar", iso3:"arg", nom:"Argentine", villes: _listeVilles("arg")},
    {region:"amerique", insee:"99416", iso2:"br", iso3:"bra", nom:"Brésil", villes: _listeVilles("bra")},
    {region:"amerique", insee:"99417", iso2:"cl", iso3:"chl", nom:"Chili", villes: _listeVilles("chl")},
    {region:"amerique", insee:"99418", iso2:"bo", iso3:"bol", nom:"Bolivie", villes: _listeVilles("bol")},
    {region:"amerique", insee:"99419", iso2:"co", iso3:"col", nom:"Colombie", villes: _listeVilles("col")},
    {region:"amerique", insee:"99420", iso2:"ec", iso3:"ecu", nom:"Équateur", villes: _listeVilles("ecu")},
    {region:"amerique", insee:"99421", iso2:"py", iso3:"pry", nom:"Paraguay", villes: _listeVilles("pry")},
    {region:"amerique", insee:"99422", iso2:"pe", iso3:"per", nom:"Perou", villes: _listeVilles("per")},
    {region:"amerique", insee:"99423", iso2:"uy", iso3:"ury", nom:"Uruguay", villes: _listeVilles("ury")},
    {region:"amerique", insee:"99424", iso2:"ve", iso3:"ven", nom:"Venezuela", villes: _listeVilles("ven")},
    {region:"amerique", insee:"99425", iso2:"ai", iso3:"aia", nom:"Anguilla", villes: _listeVilles("aia")},
    {region:"amerique", insee:"99425", iso2:"bm", iso3:"bmu", nom:"Bermudes", villes: _listeVilles("bmu")},
    {region:"amerique", insee:"99425", iso2:"ky", iso3:"cym", nom:"Caïmanes (Îles)", villes: _listeVilles("cym")},
    {region:"amerique", insee:"99425", iso2:"ms", iso3:"msr", nom:"Montserrat", villes: _listeVilles("msr")},
    {region:"amerique", insee:"99425", iso2:"tc", iso3:"tca", nom:"Turks et Caiques (Îles)", villes: _listeVilles("tca")},
    {region:"amerique", insee:"99426", iso2:"ja", iso3:"jam", nom:"Jamaïque", villes: _listeVilles("jam")},
    {region:"amerique", insee:"99428", iso2:"gy", iso3:"guy", nom:"Guyana", villes: _listeVilles("guy")},
    {region:"amerique", insee:"99429", iso2:"bz", iso3:"blz", nom:"Bélize", villes: _listeVilles("blz")},
    {region:"amerique", insee:"99433", iso2:"tt", iso3:"tto", nom:"Trinité-et-Tobago", villes: _listeVilles("tto")},
    {region:"amerique", insee:"99434", iso2:"bb", iso3:"brb", nom:"Barbade", villes: _listeVilles("brb")},
    {region:"amerique", insee:"99435", iso2:"gd", iso3:"grd", nom:"Grenade", villes: _listeVilles("grd")},
    {region:"amerique", insee:"99436", iso2:"bs", iso3:"bhs", nom:"Bahamas", villes: _listeVilles("bhs")},
    {region:"amerique", insee:"99437", iso2:"sr", iso3:"sur", nom:"Suriname", villes: _listeVilles("sur")},
    {region:"amerique", insee:"99438", iso2:"dm", iso3:"dma", nom:"Dominique", villes: _listeVilles("dma")},
    {region:"amerique", insee:"99439", iso2:"lc", iso3:"lca", nom:"Sainte-Lucie", villes: _listeVilles("lca")},
    {region:"amerique", insee:"99440", iso2:"vc", iso3:"vct", nom:"Saint-Vincent-et-Les Grenadines", villes: _listeVilles("vct")},
    {region:"amerique", insee:"99441", iso2:"ag", iso3:"atg", nom:"Antigua-et-Barbuda", villes: _listeVilles("atg")},
    {region:"amerique", insee:"99442", iso2:"kn", iso3:"kna", nom:"Saint-Christophe-et-Nieves", villes: _listeVilles("kna")},
    {region:"oceanie", insee:"99501", iso2:"au", iso3:"aus", nom:"Australie", villes: _listeVilles("aus")},
    {region:"oceanie", insee:"99502", iso2:"nu", iso3:"niu", nom:"Niue", villes: _listeVilles("niu")},
    {region:"oceanie", insee:"99502", iso2:"nz", iso3:"nzl", nom:"Nouvelle-Zélande", villes: _listeVilles("nzl")},
    {region:"oceanie", insee:"99502", iso2:"tk", iso3:"tkl", nom:"Tokelau", villes: _listeVilles("tkl")},
    {region:"oceanie", insee:"99506", iso2:"ws", iso3:"wsm", nom:"Samoa Occidentales", villes: _listeVilles("wsm")},
    {region:"oceanie", insee:"99507", iso2:"nr", iso3:"nru", nom:"Nauru", villes: _listeVilles("nru")},
    {region:"oceanie", insee:"99508", iso2:"fi", iso3:"fji", nom:"Fidji", villes: _listeVilles("fji")},
    {region:"oceanie", insee:"99509", iso2:"to", iso3:"ton", nom:"Tonga", villes: _listeVilles("ton")},
    {region:"oceanie", insee:"99510", iso2:"pg", iso3:"png", nom:"Papouasie-Nouvelle-Guinée", villes: _listeVilles("png")},
    {region:"oceanie", insee:"99511", iso2:"tv", iso3:"tuv", nom:"Tuvalu", villes: _listeVilles("tuv")},
    {region:"oceanie", insee:"99512", iso2:"sb", iso3:"slb", nom:"Salomon (Îles)", villes: _listeVilles("slb")},
    {region:"oceanie", insee:"99513", iso2:"ki", iso3:"kir", nom:"Kiribati", villes: _listeVilles("kir")},
    {region:"oceanie", insee:"99514", iso2:"vu", iso3:"vut", nom:"Vanuatu", villes: _listeVilles("vut")},
    {region:"oceanie", insee:"99515", iso2:"mh", iso3:"mhl", nom:"Marshall (Îles)", villes: _listeVilles("mhl")},
    {region:"oceanie", insee:"99516", iso2:"fm", iso3:"fsm", nom:"Micronésie (États Fédérés de)", villes: _listeVilles("fsm")},
    {region:"oceanie", insee:"99517", iso2:"pw", iso3:"plw", nom:"Palaos (Îles)", villes: _listeVilles("plw")}
];


const europe = planete.filter(x => x.region === 'europe');
const asie = planete.filter(x => x.region === 'asie');
const afrique = planete.filter(x => x.region === 'afrique');
const amerique = planete.filter(x => x.region === 'amerique');
const oceanie = planete.filter(x => x.region === 'oceanie');
const inseePays = planete.reduce((retour, {insee}) => [...retour, insee], []).filter(x => x !== "00000");

export {europe, asie, afrique, amerique, oceanie, inseePays};
