
const pdts = [
    {nom:"Adolphe Thiers", booleen:true},
    {nom:"Maréchal de Mac Mahon", booleen:true},
    {nom:"Jules Grévy,", booleen:true},
    {nom:"Sadi Carnot,", booleen:true},
    {nom:"Jean Casimir-Perier", booleen:true},
    {nom:"Félix Faure", booleen:true},
    {nom:"Émile Loubet", booleen:true},
    {nom:"Armand Fallières", booleen:true},
    {nom:"Raymond Poincaré", booleen:true},
    {nom:"Paul Deschanel", booleen:true},
    {nom:"Alexandre Millerand", booleen:true},
    {nom:"Gaston Doumergue", booleen:true},
    {nom:"Paul Doumer", booleen:true},
    {nom:"Albert Lebrun", booleen:true},
    {nom:"Vincent Auriol", booleen:true},
    {nom:"René Coty", booleen:true}
];

// https://www.assemblee-nationale.fr/13/evenements/Ceremonie_quatre-vingts/index.asp
// https://www.assemblee-nationale.fr/13/evenements/Ceremonie_quatre-vingts/les-80.asp
const parlementaires80 = [
    {nom:"Marcel Astier", booleen:true},
    {nom:"Jean-Fernand Audeguil", booleen:true},
    {nom:"Vincent Auriol", booleen:true},
    {nom:"Alexandre Bachelet", booleen:true},
    {nom:"Vincent Badie", booleen:true},
    {nom:"Camille Bedin", booleen:true},
    {nom:"Emile Bender", booleen:true},
    {nom:"Jean Biondi", booleen:true},
    {nom:"Léon Blum", booleen:true},
    {nom:"Laurent Bonnevay", booleen:true},
    {nom:"Paul Boulet", booleen:true},
    {nom:"Georges Bruguier", booleen:true},
    {nom:"Séraphin Buisset", booleen:true},
    {nom:"Gaston Cabannes", booleen:true},
    {nom:"François Camel", booleen:true},
    {nom:"Pierre de Chambrun", booleen:true},
    {nom:"Auguste Champetier De Ribes", booleen:true},
    {nom:"Pierre Chaumié", booleen:true},
    {nom:"Arthur Chaussy", booleen:true},
    {nom:"Joseph Collomp", booleen:true},
    {nom:"Octave Crutel", booleen:true},
    {nom:"Achille Daroux", booleen:true},
    {nom:"Maurice Delom-Sorbé", booleen:true},
    {nom:"Joseph Depierre", booleen:true},
    {nom:"Marx Dormoy", booleen:true},
    {nom:"Alfred Elmiger", booleen:true},
    {nom:"Paul Fleurot", booleen:true},
    {nom:"Emile Fouchard", booleen:true},
    {nom:"Edouard Froment", booleen:true},
    {nom:"Paul Giacobbi", booleen:true},
    {nom:"Justin Godart", booleen:true},
    {nom:"Félix Gouin", booleen:true},
    {nom:"Henri Gout", booleen:true},
    {nom:"Louis Gros", booleen:true},
    {nom:"Amédée Guy", booleen:true},
    {nom:"Jean Hennessy", booleen:true},
    {nom:"Lucien Hussel", booleen:true},
    {nom:"André Isoré", booleen:true},
    {nom:"Eugène Jardon", booleen:true},
    {nom:"Jean-Alexis Jaubert", booleen:true},
    {nom:"Claude Jordéry", booleen:true},
    {nom:"François Labrousse", booleen:true},
    {nom:"Albert Le Bail", booleen:true},
    {nom:"Joseph Lecacheux", booleen:true},
    {nom:"Victor Le Gorgeu", booleen:true},
    {nom:"Justin Luquot", booleen:true},
    {nom:"Augustin Malroux", booleen:true},
    {nom:"Gaston Manent", booleen:true},
    {nom:"Alfred Margaine", booleen:true},
    {nom:"Léon Martin", booleen:true},
    {nom:"Robert Mauger", booleen:true},
    {nom:"Jean Mendiondou", booleen:true},
    {nom:"Jules Moch", booleen:true},
    {nom:"Maurice Montel", booleen:true},
    {nom:"Lionel de Moustier", booleen:true},
    {nom:"Marius Moutet", booleen:true},
    {nom:"René Nicod", booleen:true},
    {nom:"Louis Noguères", booleen:true},
    {nom:"Jean Odin", booleen:true},
    {nom:"Joseph Paul-Boncour", booleen:true},
    {nom:"Jean Perrot", booleen:true},
    {nom:"Georges Pézières", booleen:true},
    {nom:"André Philip", booleen:true},
    {nom:"Marcel Plaisant", booleen:true},
    {nom:"François Tanguy-Prigent", booleen:true},
    {nom:"Paul Ramadier", booleen:true},
    {nom:"Joseph-Paul Rambaud", booleen:true},
    {nom:"René Renoult", booleen:true},
    {nom:"Léon Roche", booleen:true},
    {nom:"Camille Rolland", booleen:true},
    {nom:"Jean-Louis Rolland", booleen:true},
    {nom:"Joseph Rous", booleen:true},
    {nom:"Jean-Emmanuel Roy", booleen:true},
    {nom:"Henry Sénès", booleen:true},
    {nom:"Philippe Serre", booleen:true},
    {nom:"Paul Simon", booleen:true},
    {nom:"Gaston Thiebaut", booleen:true},
    {nom:"Isidore Thivrier", booleen:true},
    {nom:"Pierre Tremintin", booleen:true},
    {nom:"Michel Zunino", booleen:true},
];

export default [...pdts, ...parlementaires80];
